### ISSUE TITLE
Wyndon rematch trainers dont have 6 pokemon

### ISSUE THREAD

**Issue by Ganondood** [kwsch/pkNX#102]
For some reason the wyndon rematch trainers pokemon cap out at 5 in game, even though 6 are set in PKNX. I also used the randomize option to 'force set special trainers' team to 6 and it does not seem to be working. I had it successfully show 6 mons in-game prior to the tundra update.

**Comment by Ganondood** [comment]
If it helps, the wyndon rematch trainers in crown tundra seem to start from trainer #378 to #412

**Comment by sora10pls** [comment]
Not a bug. Make sure you move all edited files to your LayeredFS setup. Without the corresponding `trainer_data_xxx.bin` file, the game will load the vanilla file from the ROM (which reads 5 for # of Pokémon) and ignore the 6th slot entirely in `trainer_poke_xxx.bin`.
![image](https://user-images.githubusercontent.com/17801814/97479092-3ac04f00-1928-11eb-9e1b-12c725b7c150.png)
![Elgato Screenshot 2020-10-28 14-17-46](https://user-images.githubusercontent.com/17801814/97479208-5d526800-1928-11eb-938b-ad224cf931bd.png)
