### ISSUE TITLE
Shiny rates TM type charts 

### ISSUE THREAD

**Issue by paolito34** [kwsch/pkNX#104]
Hello 
I just updated pknx for the new 1.3 upd of pokémon Shield 
. There some things disapeard in the new pknx ? I cant edit TM , shiny rates and type chart ... I remember that was possible on my old randomized work on 1.2 
Did i missed something ? 
Thank you for helping me <3

**Comment by kwsch** [comment]
Those were only editable on LGPE games, not in SWSH games.

They currently have unused code associated to them: https://github.com/kwsch/pkNX/blame/8250f7c8120ba73d193619f8aee38ffd3ec684fd/pkNX.WinForms/MainEditor/EditorSWSH.cs#L109

but since they are not operational, they are not features.
