### ISSUE TITLE
Pancham evolution shown incorrectly

### ISSUE THREAD

**Issue by ewormPL** [kwsch/pkNX#105]
The evolution method of Pancham is unique in the games, as it evolves when there's a Dark type in the party. However, loading the game's files and looking into it, pkNX shows a list of possible arguments (the Pokémon types) with the default - as in, the correct one - being "Normal", rather than "Dark".

I assume it's a matter of the arguments being named incorrectly in the program itself and the fix might be easy.

As an aside, does this mean it is now possible to make a Pokémon evolve with a Pokémon of any chosen type in the party? Do the other arguments function properly, them being named wrong aside?

**Comment by sora10pls** [comment]
The program displaying Normal for its evolution argument means that there's no argument at all (0 = default)! The evolution method is simply mislabelled; will need to rename it and hide the argument field for that specific method.
