### ISSUE TITLE
Trainer editor level boost ratio is broken

### ISSUE THREAD

**Issue by ToxicCode87** [kwsch/pkNX#108]
If 'BoostLevel' is set to true, each time you click the randomize button, the LevelBoostRatio gets applied, causing it to stack if the Randomize button is pressed repeatedly.

If someone is like me and spams the randomize button, a temporary work around would be to enable the BoostLevel for the first press, then disable it for the subsequent clicks.

**Comment by kwsch** [comment]
You shouldn't randomize multiple times.

There already is a setting to turn off the boost completely.
