### ISSUE TITLE
Random Evolution Per Level

### ISSUE THREAD

**Issue by QorQor95** [kwsch/pkNX#109]
Hi, 

When I am randomizing evolution every level, the game won't even boot up. After randomizing, there are some missing files when compared to the original and even if I copy those missing ones, the game still won't load up

**Comment by sora10pls** [comment]
Unable to replicate using latest commit, as well as latest release of Atmosphère. Keep in mind that pkNX will only write whatever you’ve edited (and saved in each respective editor) into the generated LayeredFS folder, it’s not meant to rewrite every single file.
