### ISSUE TITLE
Generated folder is always SWORD's title ID

### ISSUE THREAD

**Issue by ewormPL** [kwsch/pkNX#110]
For some reason whether I modify Sword or Shield, pkNX always names the folder with the modified files after Sword's Title ID, never Shield's.

**Comment by sora10pls** [comment]
#79 RomFS is identical across both games.

Offset 0x290 of `main.npdm` contains the Title ID, and pkNX can be updated to grab it from this file rather than hardcode the Title IDs for LGP, LGE, SW, and SH.

**Comment by CodingKoopa** [comment]
This was fixed for the latest SwSh update with #127. The issue remains for LGPE and other SwSh versions; it may still be better to implement @sora10pls's idea to cover all of them. I hadn't seen that before implementing my PR.
