### ISSUE TITLE
Request: Allow Editing of Pokemon and Form ID Numbers

### ISSUE THREAD

**Issue by EsteeMcCrawly** [kwsch/pkNX#112]
I feel like my title is not very clear so I will explain it further.  Opening the "Pokemon" section and looking at the dropdown menu at the top it assigns a nunber to each Pokemon, like 1 to Bulbasaur and 1126 to Zygarde Complete.  Would it be possible to allow these values to be edited so for example, 1 corresponds to Hydreigon and 1126 corresponds to Togepi?

**Comment by kwsch** [comment]
They correlate to indexes within the Personal data table (personal.dat).

Adding/Inserting/Removing personal entries is not supported, as each entry that has supplementary forms would have to be repointed as well. There are other data structures that rely on the form-index ordering (such as Learnsets and egg moves), which is a little beyond the intent of the program.
