### ISSUE TITLE
little Issue with pokemon shield

### ISSUE THREAD

**Issue by Itreax** [kwsch/pkNX#113]
Hi, I got a issure wth the randomizer, when I want random wild pokemon on shield version, instead of radomize the shield category to make the random work, I need to randomize the sword category. so even of sword or shield i need to use the sword category to make the randomize working (idk if that understable )

**Comment by kwsch** [comment]
Search the list of issues:
https://github.com/kwsch/pkNX/search?q=shield&type=issues

https://github.com/kwsch/pkNX/issues/110
