### ISSUE TITLE
Game Crashes when opening pokedex after randomizing Shield

### ISSUE THREAD

**Issue by OliviaSama** [kwsch/pkNX#115]
[https://drive.google.com/drive/folders/1NhQEhj4Vi96rWghAKeqf1EQN2esHgHBc?usp=sharing](url) I linked my crash reports; but I noticed after randomizing my shield copy that I was unable to load into my pokedex at all. I've narrowed down after trial and error removing one group of files at a time that it's a data_table.gfpak issue, just I'm not sure how to go about fixing this. I tried randomizing as well afterwords off the sword encounters after seeing some other people mention data table related things here and figured it was worth a try, but neither data table ended up working. If anyone has any idea how to fix this that'd be great; or if this is just a pkNX issue specifically then any sort of fix to this would also be very appreciated!

**Comment by kwsch** [comment]
I'll assume you randomized wild encounters, but did you enable the setting to fill empty slots?

@sora10pls is this the habitat stuff you mentioned earlier?

**Comment by sora10pls** [comment]
Yeah, it is. Here's an excerpt from when I looked further into your forum post:
![image](https://user-images.githubusercontent.com/17801814/101509149-75b19b80-3946-11eb-8410-5b27635d91ba.png)

**Comment by OliviaSama** [comment]
oh that's awesome; i wasn't sure if that thread was dead or not so i figured i'd report the issue here. thank you both for looking into this I genuinely really appreciate the help here!
