### ISSUE TITLE
Pokemon Typings Not Changing or Randomizing

### ISSUE THREAD

**Issue by EclispedPsycho** [kwsch/pkNX#119]
So, for weeks I been having odd issues with Pknx not randomizing Pokemon types or those I did customly, and stats don't change either. Like I tried making thwackey a Grass/Psychic and then go ingame, thwackey remained Grass. I did hit save, and exit the program. I'm not sure if it has something to do with Yuzu or Pknx. I mean, wild Pokemon at least randomize but typings don't. Cause I did have Yuzu dump the game, and Pknx works with it. Sadly changing Pokemon's typings don't work. I do got the update 1.3.0 for the game, and Yuzu installed it.
![0100abf008968000_2021-02-02_01-56-08-016](https://user-images.githubusercontent.com/78405066/106563911-828fdd00-64fa-11eb-9529-64e2e424da77.png)
![Capture](https://user-images.githubusercontent.com/78405066/106563914-83c10a00-64fa-11eb-8cae-4ce381fbc66d.PNG)

**Comment by kwsch** [comment]
You're doing something wrong. Game data doesn't remember what it used to be; it only knows what it is.
