### ISSUE TITLE
dynamax adventure 

### ISSUE THREAD

**Issue by bob24170** [kwsch/pkNX#125]
First, I would like to thank yous for your time and help.

My first question is that is—is there a known way to mod dynamax adventure yet? If no, then the following questions may not need to be answered.

Second, I realise that modding dynamax adventure is hard. But is there some known mod-able components that wont crash the dynamax adventure, please? 

Finally, I just wanna say that I absolutely love dynamax adventure part of the game. It is ok if I can’t now, hopefully  one day, it will be mod-able and can be played.

**Comment by sora10pls** [comment]
#103
