### ISSUE TITLE
Error with pknx

### ISSUE THREAD

**Issue by lrlcksla** [kwsch/pkNX#130]
For some reason even though it says I have 50,494 files in my romfs folder when I open it up in pknx and the error is that I'm missing files in"bin/message/English/common" and when I click continue it doesn't do anything, I've tried different methods of getting the files via nxdump and the result appears consistently and I haven't been able to get any help on the situation either.

**Comment by kwsch** [comment]
The program works fine; if the program tells you that you're missing files, then your dump is either incomplete/bad.

**Comment by lrlcksla** [comment]
> The program works fine; if the program tells you that you're missing files, then your dump is either incomplete/bad.

Ive tried multiple ways with nxdump and all lead to the same result and it says I have 50,494 files in my romfs folder which I looked up is the exact amount I should have. I've even uninstalled and reinstalled nxdump but it still lead to same result. And your one line is the most detail in a response I have received and I still don't know where or what I am doing wrong.
