### ISSUE TITLE
Increase raid den boss level 

### ISSUE THREAD

**Issue by bob24170** [kwsch/pkNX#131]
First, I would like to thank you for your time and help.

I realise that raid den boss level is related to badge numbers. And I have finished 8 badges. I want to ask is it possible to edit both common and rare dens’ bosses levels to 100 lvl in my situation(8 badges) with pknx.

**Comment by kwsch** [comment]
Would require modifications to the code; custom code edits aren't supported in pkNX, and it's not something that many people would use (unlike shiny rate editing), so it's not something I'm interested in doing.
