### ISSUE TITLE
Error when trying to build with Visual Studio 2019

### ISSUE THREAD

**Issue by JakiStow** [kwsch/pkNX#132]
Using Visual Studio 2019 to build the code, I get multiple warnings saying "Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)"

See picture attached:
![Error](https://user-images.githubusercontent.com/80118365/110146783-442c5d00-7ddb-11eb-84b7-7db6e928f937.png)

I just installed Visual Studio 2019, did I miss something?

**Comment by sora10pls** [comment]
I suggest you read through a similar issue here (solution provided lower): https://github.com/kwsch/PKHeX/issues/3169

Nothing wrong with pkNX, so closing as this is a Visual Studio regression.

**Comment by JakiStow** [comment]
Thank you!
