### ISSUE TITLE
save function in the trainer editor

### ISSUE THREAD

**Issue by bob24170** [kwsch/pkNX#136]
First, I would like to thank you for your time and help.

After I save the changes to trainers’ pokemon moves in ‘trainer editor’, it crash me out of the trainer editor and into the main panel( with the ‘pokemon’ ‘trainer’ ‘dynamax adventure’ buttons). And when I went back to the trainer editor, my changes were not save. Is there something wrong that I did, please?

**Comment by kwsch** [comment]
Please post a more detailed description of the error, preferably whatever the program says, verbatim.

**Comment by bob24170** [comment]
> Please post a more detailed description of the error, preferably whatever the program says, verbatim.
Figured out, got to hit ‘set’ also.
