### ISSUE TITLE
Pokechange AI flag is incorrect

### ISSUE THREAD

**Issue by Kobazco** [kwsch/pkNX#138]
I posted this on the Project Pokemon thread, but I thought I might as well open up an actual issue about this.

Enabling the "Pokechange" AI flag doesn't actually do anything, the AI never swaps out their Pokemon even if they have a situation where they would've in previous games. I know that the Pokechange AI actually does exist, as battle tower trainers use it. There's also a file for it in the folder with the rest of the AI. I tried doing some poking around in terms of hex editing trainer data myself, but... There's no reference for any trainers outside of the battle tower that actually swap out their Pokemon.

I know many others would appreciate it if the Pokechange option was fixed/at least looked into some more. Thanks in advance.

**Comment by kwsch** [comment]
As I mentioned on the forums, the game logic might not check that flag for the regular in-game battles.

**Comment by Kobazco** [comment]
Thanks for clarifying what you said on the forums. To me it seemed like you said the game didn't use the previously thought to be flag, or that it may be in a different order. 

If that's the case, well that's just really unfortunate.
