### ISSUE TITLE
Folder is Invalid Alert, but all of the correct game files are there

### ISSUE THREAD

**Issue by HenryHeliolisk** [kwsch/pkNX#139]
Invalid folder Loaded
Unable to recognize game data.

This is what I get. After the error i got yesterday, I read the readme, and dumped the game with the correct updates, but now it wont recognize it at all. Is this because I needed to use the DLC instead of the update when dumping? It is an extremly lengthy process that I just want to mimimalize.

**Comment by sora10pls** [comment]
Expected filecount is 50,494 in RomFS. Works fine with both of my dumps (Sword & Shield, respectively) so double check your dump.

**Comment by HenryHeliolisk** [comment]
mine says 50,517, of which should I delete?
