### ISSUE TITLE
Couldn't find part of the patch

### ISSUE THREAD

**Issue by Sumhoo** [kwsch/pkNX#142]
Hello, I have dumped both exeFS and romFS from my copy of Shield but when I tried to load my game files into the application I got this error. 

Any advice on the issue?

![hmmm](https://user-images.githubusercontent.com/81455084/112708852-f6ab8900-8e8a-11eb-90e7-889784464fc6.PNG)

**Comment by kwsch** [comment]
pkNX needs to load files from that folder; failing to load files results in that error.

I suspect your Desktop is a OneDrive folder, and the files are not kept-local (aka, on the cloud).
