### ISSUE TITLE
Game Not Randomizing after putting it into Atmosphere Titles Folder

### ISSUE THREAD

**Issue by Sumhoo** [kwsch/pkNX#143]
Hello,

I was able to load all my romfs stuff into pknx, and after randomizing everything I get the patch file, after putting it into my atmosphere titles folder and load up the game, nothing has changed.

The title id folder output from pknx is 01008DB008C2C000 but the title id i choose when doing nxdumptool for the romfs is 01008DB008C2C**_8_**00 the only difference being that 8, yet pknx is loading it just fine.

Is there anything im missing as to why the game doesnt recognize that it should be randomized?

**Comment by MegaKBang** [comment]
The folder has to be called "contents" and not "titles"

**Comment by sora10pls** [comment]
`01008DB008C2C000` is being read directly from your ExeFS dump, and is the title ID for Shield 1.3.1.

Tested with my own Shield dump and ingame, working as intended. Make sure you're doing what @MegaKBang has suggested, as this was changed in Atmosphère a while ago.
