### ISSUE TITLE
Trainer Randomization not working

### ISSUE THREAD

**Issue by Sumhoo** [kwsch/pkNX#144]
Hello,

It seems I'm able to randomize everything in the game except what other Pokemon that trainers use in battle, for example I'll randomize and save everything correctly but when i load up the game, the first battle with Hop he sends out a Wooloo and the opposite type starter.

Any advice on how I can remedy this?

**Comment by sora10pls** [comment]
Make sure you’re clicking save when randomizing trainer data with pkNX; if other edits are being loaded in correctly, then it’s likely because you didn’t randomize/move over modified trainer data.
