### ISSUE TITLE
pkNX crashes on opening folder

### ISSUE THREAD

**Issue by Fudgecake4567** [kwsch/pkNX#146]
Whenever I click the folder that has the files set up inside of it, I get the error "Index was outside the bounds of the array", and every tutorial I've seen has done the exact same thing and it worked properly.

**Comment by sora10pls** [comment]
https://github.com/kwsch/pkNX/blob/master/README.md#features

Those tutorials can be (and likely are) outdated. Re-dump your game with the necessary patch.

**Comment by Fudgecake4567** [comment]
I still can't find a reliable source to say how to do it, and everything official seems cryptic and confusing

**Comment by kwsch** [comment]
Obtaining the correct game dumps to use with the program is not an issue with the program.
