### ISSUE TITLE
Cannot edit file in pkNX, dumped multiple times still doesnt work.

### ISSUE THREAD

**Issue by smrtg** [kwsch/pkNX#150]
![20210430_210623](https://user-images.githubusercontent.com/30999558/116786973-40028000-aaaa-11eb-880b-8734f12ca1a8.jpg)
Error details;
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\Users\spyfr\Desktop\shield\ExeFS\main.npdm'.
File name: 'C:\Users\spyfr\Desktop\shield\ExeFS\main.npdm'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at pkNX.Game.GameLocation.<GetGameFromCount>g__GetTitleID|22_0(<>c__DisplayClass22_0& )
   at pkNX.Game.GameLocation.GetGameFromCount(Int32 fileCount, String romfs, String exefs)
   at pkNX.Game.GameLocation.GetGame(String dir)
   at pkNX.WinForms.Controls.EditorBase.GetEditor(String loc, Int32 language)
   at pkNX.WinForms.Main.OpenFolder(String path)
   at pkNX.WinForms.Main.Menu_Open_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
pkNX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/pkNX.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/System.Resources.Extensions.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/System.Numerics.Vectors.DLL
----------------------------------------
pkNX.Structures
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/pkNX.Structures.DLL
----------------------------------------
pkNX.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/pkNX.Game.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by sora10pls** [comment]
You’re not using the latest commits. This has already been fixed: https://github.com/kwsch/pkNX/commit/ae42c5ea45def573359627915e16dbc034bd0629

**Comment by smrtg** [comment]
> You’re not using the latest commits. This has already been fixed: [ae42c5e](https://github.com/kwsch/pkNX/commit/ae42c5ea45def573359627915e16dbc034bd0629)

I'm using the latest version on azure or whatever that site is. Dunno how to compile stuff from github

**Comment by sora10pls** [comment]
Unable to replicate using the latest build from Azure Pipelines. My original comment still stands.
![image](https://user-images.githubusercontent.com/17801814/116792467-bd1ffc00-aa8e-11eb-895b-837f838dc538.png)

**Comment by smrtg** [comment]
Went from the guide to the azure link provided there, clicked on the latest
one uploaded on April 22nd and I'm getting this error.

**Comment by sora10pls** [comment]
As I mentioned, it could also mean that your ExeFS dump is incomplete. Either re-dump ExeFS with hactool or nxdumptool, or exclude it from your loaded ROM (pkNX doesn't offer any ExeFS editing for SWSH at the moment, anyway).

**Comment by smrtg** [comment]
That file does exist in my ExeFS folder, so i dont know why its saying its missing.
Without the ExeFS folder i get this error:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\spyfr\Desktop\shield\RomFS\bin\message\English\common'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at pkNX.Containers.FolderContainer.Initialize(Func`2 filter)
   at pkNX.Game.GameManager.GetFilteredFolder(GameFile type, Func`2 filter)
   at pkNX.Game.GameManagerSWSH.Initialize()
   at pkNX.Game.GameManager..ctor(GameLocation rom, Int32 language)
   at pkNX.Game.GameManager.GetManager(GameLocation loc, Int32 language)
   at pkNX.WinForms.Controls.EditorBase.GetEditor(String loc, Int32 language)
   at pkNX.WinForms.Main.OpenFolder(String path)
   at pkNX.WinForms.Main.Menu_Open_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
pkNX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/pkNX.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/System.Resources.Extensions.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/System.Numerics.Vectors.DLL
----------------------------------------
pkNX.Structures
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/pkNX.Structures.DLL
----------------------------------------
pkNX.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/pkNX.Game.DLL
----------------------------------------
pkNX.Containers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/spyfr/Downloads/pkNX/pkNX/net461/pkNX.Containers.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


![IMG_20210501_222838](https://user-images.githubusercontent.com/30999558/116793045-055e0f00-aacd-11eb-82f9-a3897a535959.jpg)

**Comment by kwsch** [comment]
Probably OneDrive isn't storing your desktop files locally on your hard drive.

The error messages are pretty clear.

**Comment by smrtg** [comment]
I don't even have one drive installed. I know that the error message says
it can't find a file or smth, but I have no idea why

**Comment by kwsch** [comment]
Files don't magically not exist. Confirm that files are present in the folder, and that you're using the complete unpacked game with the latest patch content.

**Comment by smrtg** [comment]
I have checked and I have dumped the game multiple times. With nxdumptool,
choosing the update (and not a dlc or smth like that) and trying to open on
in the latest version of pkNX from azure. The files do exist in their
respective folders when I manually check and I have no cloud storage
thingies so all my files are definitely local.

**Comment by kwsch** [comment]
Screenshot the file inside the folder, please.

OneDrive is installed by default on all Windows 10 machines.

**Comment by smrtg** [comment]
I have uninstalled OneDrive from my pc myself. I moved the folder to the root of my drive still the same issue. Here are some screenshots of RomFS/"gameid"/bin/message/English/common, aka the folder in the error.
https://gyazo.com/bc318d4ae0af893aecfb54835105b8c7
https://gyazo.com/fbbb5e0ae24398fa522ae395b80aab0a
https://gyazo.com/6485e5da5549f5bba35f60dd86df0dc8

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/116797344-961af780-aa99-11eb-9296-6a007becf216.png)

![image](https://user-images.githubusercontent.com/6393368/116797348-a3d07d00-aa99-11eb-8393-937e8294c8c5.png)

These aren't the same folder (UPD, v+numbers). The update has to be merged into the base ROM's content, yielding a complete ROM on the latest patch.

**Comment by smrtg** [comment]
I just moved the same folder to the root of the drive as you told me before
the screen shots.

**Comment by smrtg** [comment]
Though I just noticed that the pok_mon folder isn't mentioned on the error at all. What the?

**Comment by smrtg** [comment]
Okay it worked now, I moved the folders inside the pok_mon folder up to the main romfs folder and now it works. The problem was the pok_mon folder. PkNX was trying to find romfs/bin but after the dump the folder was romfs/pok_mon/bin

**Comment by wess9595** [comment]
hi, i recently have the same problem but dont know what exactly have to do :(

![image](https://user-images.githubusercontent.com/114990311/193786642-0a4efba9-a3cb-4b70-88a9-ef759b3d8111.png)

**Comment by JelleInfinity** [comment]
@wess9595 If you click OK, can you still press "File -> Open..."? If so you can select the new location of your dumped files.
As the error is telling you, it's looking for a file in your OneDrive folder. Probably because you had it located there before.

**Comment by wess9595** [comment]
oh how can i change the locagion of dumped files?

**Comment by JelleInfinity** [comment]
press "File -> Open..."

**Comment by wess9595** [comment]
ok

**Comment by wess9595** [comment]
![image](https://user-images.githubusercontent.com/114990311/193798183-81e1a195-21e5-4551-addf-dbdbedd6b081.png)

**Comment by JelleInfinity** [comment]
Yes, now select the folder with your dumped files

**Comment by wess9595** [comment]
ok it selected

**Comment by wess9595** [comment]
![image](https://user-images.githubusercontent.com/114990311/193798511-588504c4-0c79-457c-9396-67acff0b314c.png)

**Comment by wess9595** [comment]
bro?

**Comment by wess9595** [comment]
mmm but still show me this 

![image](https://user-images.githubusercontent.com/114990311/193800058-392cb48a-9571-481e-bda2-a40924ec06c7.png)

**Comment by wess9595** [comment]
mm but still show mw this 

![image](https://user-images.githubusercontent.com/114990311/193800131-01ff6537-fb87-4981-9491-5c3133039a27.png)

**Comment by JelleInfinity** [comment]
Okay, in that case you might be selecting a folder shortcut that no longer exists. You have to select the full folder path

**Comment by wess9595** [comment]
have to do file - open again+?

**Comment by JelleInfinity** [comment]
I've push a new code change that will help me, help you.

Could you please update your pkNX with the link below:

https://dev.azure.com/project-pokemon/pkNX/_build/results?buildId=5610&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by wess9595** [comment]
prees template button? 

![image](https://user-images.githubusercontent.com/114990311/193803260-e622d177-6e27-4c4c-9e55-3b46db6f267e.png)

**Comment by JelleInfinity** [comment]
No, File -> Open

**Comment by wess9595** [comment]
ok 

![image](https://user-images.githubusercontent.com/114990311/193803656-e1ea739f-c1cf-4fac-929b-83b1199f6578.png)

**Comment by JelleInfinity** [comment]
Yes, now click select folder

**Comment by wess9595** [comment]
ok 

![image](https://user-images.githubusercontent.com/114990311/193803853-3602ee48-8dd8-40f9-8481-ed87ff8b20f8.png)

**Comment by JelleInfinity** [comment]
I mean the button next to cancel

**Comment by wess9595** [comment]
:'(

![image](https://user-images.githubusercontent.com/114990311/193804080-99f9595c-f5f1-471e-a228-f0d23ef1fa55.png)

**Comment by JelleInfinity** [comment]
You're looking at your one drive desktop folder. That folder doesn't exist

**Comment by wess9595** [comment]
yeah but i dont know why it still open in that dam folder :(

**Comment by JelleInfinity** [comment]
Because it's a fake folder. Windows for some reason kept the shortcut to your one drive folders. You should delete it

**Comment by JelleInfinity** [comment]
Please Open file explorer;
![image](https://user-images.githubusercontent.com/60387522/193805420-3e5651ab-20ce-4aca-9455-f8faa01322ff.png)
Go to Local Disk (C:)
![image](https://user-images.githubusercontent.com/60387522/193805509-f3a63263-1993-4049-9819-a3b0a3bedfec.png)

**Comment by JelleInfinity** [comment]
Users
![image](https://user-images.githubusercontent.com/60387522/193805580-bb57ff69-ee3c-466c-9d1b-d3deedd14738.png)

Go to webst

Click OneDrive
![image](https://user-images.githubusercontent.com/60387522/193805749-e32bc4a9-f7b0-4e09-abe8-3694e88006d3.png)

And delete that folder

**Comment by wess9595** [comment]
ok its already delete

**Comment by JelleInfinity** [comment]
Ok, now show me the full path to your dumps in explorer

**Comment by wess9595** [comment]
bro all files have been deleted  

![image](https://user-images.githubusercontent.com/114990311/193807217-e02a1d15-bf69-4232-8f1c-0baf4296fe6f.png)

**Comment by JelleInfinity** [comment]
Yes, good, because again, you are looking at the wrong folder.
Go to C:\Users\webst\Desktop <- that's the correct desktop folder

**Comment by wess9595** [comment]
all my desktop hace been deleted :,d

![image](https://user-images.githubusercontent.com/114990311/193807945-40355fd6-1167-4758-808e-1de63fc18d7a.png)

**Comment by JelleInfinity** [comment]
Did you have one of those "zero hard drive space, so you're forced to use one drive" laptops?

**Comment by JelleInfinity** [comment]
Fyi, all your files are still in the Recycle bin. Just open it and restore

**Comment by JelleInfinity** [comment]
It was there in your last image?

**Comment by JelleInfinity** [comment]
Anyway, again show me this folder please > C:\Users\webst\Desktop

**Comment by wess9595** [comment]
![image](https://user-images.githubusercontent.com/114990311/193809858-041334ae-5b26-4766-8cff-0ff34884b12a.png)

**Comment by JelleInfinity** [comment]
Okay, I see what happend.. One sec

**Comment by JelleInfinity** [comment]
Please download and install recuva to restore your deleted files: https://www.ccleaner.com/recuva/download/standard

**Comment by JelleInfinity** [comment]
Once installed, make sure you keep all files selected
![image](https://user-images.githubusercontent.com/60387522/193810370-cf9e8cb7-baa6-4252-be5e-73335182a6ce.png)

**Comment by JelleInfinity** [comment]
Type location as shown in image below:
![image](https://user-images.githubusercontent.com/60387522/193810568-65d85e6a-12f3-4c7f-9283-d7be0d47cff1.png)

**Comment by wess9595** [comment]
ok ill try it

**Comment by JelleInfinity** [comment]
Make sure you enable deep scan:
![image](https://user-images.githubusercontent.com/60387522/193810765-16ad12cc-223b-4c57-ba53-de753c346123.png)

**Comment by wess9595** [comment]
when i put soecific location - not shot the  path, that doesnt matter?

![image](https://user-images.githubusercontent.com/114990311/193811007-7ca1dccf-0a37-4864-b8c1-63d2728b14aa.png)

**Comment by JelleInfinity** [comment]
Just click next

**Comment by JelleInfinity** [comment]
Once done; select all files
![image](https://user-images.githubusercontent.com/60387522/193811109-dc0fc69a-7869-4521-8e7e-761567b495bf.png)
And click Recover...
![image](https://user-images.githubusercontent.com/60387522/193811250-0c934bf8-2950-4412-88a5-cd75d0eb9000.png)

**Comment by wess9595** [comment]
![image](https://user-images.githubusercontent.com/114990311/193813463-dd13324d-5ec1-420e-80f6-ab6ef0ddc25d.png)

**Comment by JelleInfinity** [comment]
Okay, now that you have recovered the folder, you should cut all the items from `\[RecoverFolder]\OneDrive\Desktop\` to `C:\Users\webst\Desktop`

**Comment by wess9595** [comment]
ill try again because , the archives dont open 

![image](https://user-images.githubusercontent.com/114990311/193814994-90365e92-2431-4b38-95b2-cb458c3ed7e7.png)

**Comment by JelleInfinity** [comment]
I would recommend not doing that again

**Comment by JelleInfinity** [comment]
The more you modify the contents of the free space on your drive the bigger the chance of corrupted files. If they don't load now, chances are they have already been corrupted

**Comment by JelleInfinity** [comment]
Also, not that since you didn't get the option to select a folder, it also added files that might be super old

**Comment by wess9595** [comment]
mmmm well guess thats it , but well i will have fun doing all again xD

**Comment by wess9595** [comment]
look bro , i try to move the dump folder from one drive folder to download folder ant still, the error, guess the problem is that exefs/ main.npdm , if you see this please let me know what you think 

![image](https://user-images.githubusercontent.com/114990311/193821170-e87e9b78-6419-4b64-9bce-12fa1d67a8d0.png)

**Comment by JelleInfinity** [comment]
No, as we've established. It has nothing to do with OneDrive. You are actually missing the file from your dumps

**Comment by wess9595** [comment]
well at last i can did it , at least  something good of all this xD, anyway thanks a lot for helping and sorry for quiting many time of yours buddy 

![image](https://user-images.githubusercontent.com/114990311/193841652-f99fd500-72f1-44df-99e3-b8968bf8e9eb.png)

**Comment by JelleInfinity** [comment]
You're welcome, happy modding

**Comment by wess9595** [comment]
hey bro , you know if it possible to modify or change background music to custom music of the pokemon rom - sword, letsgo etc

**Comment by JelleInfinity** [comment]
It's possible, but this isn't the right place to ask. Nor am I the person to ask, since I've never done that before.

**Comment by JelleInfinity** [comment]
Hmm, yes. In that case, I'm sorry for giving incorrect information.I suppose you are actually missing that file in your dumps then. Did your dump include game updates?On 4 Oct 2022 14:41, wess9595 ***@***.***> wrote:
look bro , i try to move the dump folder from one drive folder to download folder ant still, the error, guess the problem is that exefs/ main.npdm , if you see this please let me know what you think
