### ISSUE TITLE
Type/Stats Will Not Randomize

### ISSUE THREAD

**Issue by RuinousPrincess** [kwsch/pkNX#151]
Some reason stats and or types will not randomize for me. I have re-downloaded PKNX dozens of times over the past month, but it won't work for me. I left the settings on default, still won't work, I changed some stuff, and it still won't work. 

I've even went and changed the base stats of Sobble to 255, and changed it to a Water/Ground type, hit save, and went back to check and the setting was saved for the Pokémon tab. Done this for PK3DS and it works. Strange thing, nothing will reflect in game. The settings, types, stats were saved, and changed but not appearing in-game. Not sure if it's PKNX not working or what, cause I can randomize Pokémon without a single issue. A little help would be nice. Using this for Yuzu.

**Comment by kwsch** [comment]
> The settings, types, stats were saved, and changed but not appearing in-game.

Not a pkNX issue. You'll have to troubleshoot why your modified files are not being loaded by the emulator.

**Comment by RuinousPrincess** [comment]
How do I exactly troubleshoot it? I got no idea on how to do that for Yuzu.

**Comment by kwsch** [comment]
> How do I exactly troubleshoot it? I got no idea on how to do that for Yuzu.

Loading game mods with an emulator is unrelated to this program. Again, pkNX is not your issue.
