### ISSUE TITLE
Invalid folder loaded

### ISSUE THREAD

**Issue by zeldaking** [kwsch/pkNX#153]
So the first time I used this it worked but I accidently deleted my romfs dump without knowing it and emptied my recycling bin. I re-dumped my romfs but when I put it into pknx it says 

"Invalid folder loaded.
Unable to recognize game data.

C:\Users\"Me"\AppData\Roaming\yuzu\dump\0100187003A36000"

![image](https://user-images.githubusercontent.com/43257330/121571903-7223cd80-c9d8-11eb-9783-07340dcb8f0b.png)

**Comment by kwsch** [comment]
Likely not a complete dump / polluted dump.
pkNX expects a specific count of files.

https://github.com/kwsch/pkNX/blob/4e6fbe78ed251a8bc22abacdbb1fbd5eea8b475e/pkNX.Game/GameLocation.cs#L40-L121
