### ISSUE TITLE
show names in gift static trade editors + legendary for legendary?

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/pkNX#16]
right now next to species it shows the pokedex number (ex. pikachu is 25 and eevee is 133 in the gift editor )  same for items, relearn moves and special moves (nature is ok it shows their names ). can this be changed to show their actual names instead ? for example instead of showing 133 it shows eevee . also if possible add legendary for legendary randomizer like pk3DS has ?

**Comment by egzonqj** [comment]
I don't know what plans @kwsch has for the forms that are currently text-only (such as the Static one), I might PR this issue tho
