### ISSUE TITLE
Error saying Index was outside the bounds of array

### ISSUE THREAD

**Issue by Pokemanix** [kwsch/pkNX#161]
Yes i read the readme, no it did not help.

**Comment by Pokemanix** [comment]
In addittion to my initial problem, i dumped an xci which already to my knowlege already had the patch in it. If there is a way to merge in the patch please let me know and ill test it out and get back to you with the results. Please and thank you.

**Comment by kwsch** [comment]
> i dumped an xci which already to my knowlege already had the patch in it

Dump your own ROMs; support is not provided for pirated game copies.

**Comment by Pokemanix** [comment]
ok, i own pokemon sword so if theres a way to dump those files could you point me in the direction of a guide or tutorial
