### ISSUE TITLE
I want to ask whether dynamax adventure is mod-able now

### ISSUE THREAD

**Issue by bob24170** [kwsch/pkNX#162]
First, I would like to thank you for your time and help.

I want to ask whether dynamax adventure is mod-able now with pknx. I think with the older versions, you get a crash when you mod dynamax adventure.

**Comment by kwsch** [comment]
No.

https://github.com/kwsch/pkNX/search?q=dynamax&type=commits

Likely nobody will take the time to investigate why, as people abused the Raid editing online in the past.
