### ISSUE TITLE
839 - Monthracite (Stage: 0)

### ISSUE THREAD

**Issue by arobase-che** [kwsch/pkNX#172]
Why does Coalossal is Stage 0 ?

It should be Stage 3, doesn't it ?
In French, the file `Pokemon.txt` contains:
~~~
======
839 - Monthracite (Stage: 0)
======
~~~

I'm expecting :
~~~
======
839 - Monthracite (Stage: 3)
======
~~~

**Comment by kwsch** [comment]
Because that's how the game developers decided to specify that value for that species.

**Comment by arobase-che** [comment]
Thank you for you answer.
That is so weird !
