### ISSUE TITLE
Not an issue, just a question...

### ISSUE THREAD

**Issue by Mindinfinity2** [kwsch/pkNX#176]
Hi, guys just wanted to ask if anyone knew where in the **RomFs** or **ExeFs** folders is the **"Ability"** data stored? My goal is to try and hex edit the ability, **_"As One"_** so that it is no longer a combination of **"Unnerve"** and **_"Chilling/Grim Neigh"_**, but 2 very different abilities.

If this is not possible let me know as well. Thx.

**Comment by kwsch** [comment]
exefs

**Comment by Mindinfinity2** [comment]
Thank you.

**Comment by Mindinfinity2** [comment]
Appreciate the help however I don't thin I'm going to be able to do this. Installed Ghidra and Java, however everything from here seems far beyond my level of understanding. The complexity in trying to do this would probably require me to have knowledge in coding, which I do not. I thought this would be as easy as finding the correct file in ExeFS folder and simply hex editing it, clearly not. If there is guide I could follow I could do this I'm sure, or if I could ask someone to do it I would not mind paying them.

**Comment by Mindinfinity2** [comment]
> exefs, find whatever routine in the battle logic does it.
> 
> disassemble the code with ida/ghidra and make a code patch to make the instructions behave differently

Appreciate the help however I thought this would be as easy as finding the correct file in ExeFS folder and simply hex editing it, clearly not. If there is guide I could follow I could do this I'm sure, or if I could ask you to do this for me I am more than willing to pay, just name your price.

Thanks.
