### ISSUE TITLE
Invalid Folder loaded - Unable to Recognize Game Data (Pokemon Sword 1.3.1)

### ISSUE THREAD

**Issue by Hidlsh** [kwsch/pkNX#177]
Firstly; yes, I've googled many things but with no luck to finding the solution, so I came here.

**Current Issue:**
![image](https://user-images.githubusercontent.com/67646781/147423309-ee3ab7c1-5cad-4345-bc64-42b88d702c88.png)
Is the current pkNX version (downloaded it today Dec 26th, 2021) compatible with Pokemon Sword 1.3.1? (Images down below)

**Current progress in Pokemon Sword:**
I've just defeated the 2nd gym leader (water girl - forgot her name)

**Info on what I've done so far to try and set up pkNX:**
1. Dumped romFS 'Base' (Full, not skeleton),
2. Copied that folder to desktop
3. Deleted original **dumped** folder from Yuzu 'dump' folder
4. Renamed the **dumped** "Pokemon Sword Dump"
5. Launched pkNX then added the "Pokemon Sword Dump" folder and got the error: "_Invalid Folder loaded - Unable to Recognize Game Data._"

**Current progress in Pokemon Sword:**
I've just defeated the 2nd gym leader (water girl - forgot her name)

**Inside my current pkNX version folder:** 
![image](https://user-images.githubusercontent.com/67646781/147423622-d2704654-c4f7-40e4-9eb9-6e0676b80b8c.png)

**Current progress in Pokemon Sword:**
I've just defeated the 2nd gym leader (water girl - forgot her name)

**My dumped (renamed) folder**
(main.ndpm save file located inside ExeFS folder - 1,566KB)
![image](https://user-images.githubusercontent.com/67646781/147423332-786a5eef-1437-4b6f-8166-791cc3c47c00.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/pkNX/issues/153#issuecomment-859104273
