### ISSUE TITLE
Can't add more than one extra evolution method to eevee.

### ISSUE THREAD

**Issue by Flicks1** [kwsch/pkNX#178]
I'm making a mod and have 2 new eevelutions, but i can only add one evolution method and I also tried hex editing it.

**Comment by sora10pls** [comment]
Sword and Shield only support 9 possible evolution paths. This was upped from Generation 6 and 7’s cap of 8 to accommodate for Sylveon, and was upped to 9 to accommodate for Alcremie’s 9 forms.

Increasing this cap is beyond the scope of pkNX.
