### ISSUE TITLE
Error message when trying to build

### ISSUE THREAD

**Issue by tkdfredrik04** [kwsch/pkNX#182]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1617	Invalid option '10' for /langversion. Use '/langversion:?' to list supported values.	pkNX.Structures (netstandard2.0)	C:\Users\fresk\Source\Repos\pkNX legends\pkNX.Structures\CSC	1	Active
 keep getting these error messages on all the pkNX files when im trying to make it in visual studios

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.	pkNX.Tests	C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	141	
also got that one

**Comment by kwsch** [comment]
The error message you posted indicates what the fix is:

> Error NETSDK1045 The current .NET SDK does not support targeting .NET 6.0. Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.

Install .NET 6.0; things were upgraded in the latest commits.
