### ISSUE TITLE
Save button inaccessible for trainers

### ISSUE THREAD

**Issue by ReservedJV** [kwsch/pkNX#184]
![image](https://user-images.githubusercontent.com/32025584/152657772-b6b03d73-5735-467d-9125-8d1c53182c26.png)

Is the save button for trainers supposed to be inaccessible? All the other windows that open have their save buttons enabled, so I'm not sure if this is currently intentional or on my side.

**Comment by kwsch** [comment]
I don't think the flatbuffer was completely reverse engineered and verified that saving works, hence the save button not being enabled in the generic editor.
