### ISSUE TITLE
[PLA] Get Full Odds even with "Pokedex Research Perfect"

### ISSUE THREAD

**Issue by Valnoob** [kwsch/pkNX#185]
Hi, I do not understand which value I need to put in to have 1/4096 Odds to encounter a shiny even if my dex entries are Level 10 or Complete. 

Could you just tell me which number I need to put in please. 

Thanks
![image](https://user-images.githubusercontent.com/99076747/152676495-d5b58b90-2ecc-4d0d-8ca3-54d20e244792.png)

![image](https://user-images.githubusercontent.com/99076747/152676504-fd0b6b9d-afa3-4ab0-8710-75c5313b848d.png)

![image](https://user-images.githubusercontent.com/99076747/152676505-71afacb7-3654-4325-adf7-2049af3f0da3.png)

**Comment by sora10pls** [comment]
`ConfiguredValue` stores additional Shiny rerolls depending on what the condition is.

`TryCount_Item` = Shiny Charm, which grants +3 rerolls.
`TryCount_Research100` = 100 Research Points (Research Level 10), which grants +1 rerolls.
`TryCount_ResearchPerfect` = Perfect Research Level, which grants +2 rerolls.

**Comment by Valnoob** [comment]
Thanks !
