### ISSUE TITLE
[Sword] Wild pokemon not affected by edits after Slumbering Weald

### ISSUE THREAD

**Issue by VinCramer** [kwsch/pkNX#186]
I've tested this on both Yuzu 911 and Ryujinx 1.1.20 for Sword v 1.3.2, with both DLCs. The other aspects of the randomizer are working fine - the trainer encounters are randomized, and the starter pokemon are too.

However, when the wild spawns are randomized, the spawns in Slumbering Weald will be random, but the ones for Route 1 and beyond will not be changed. I've tried creating standalone mods that just randomize the wild encounters, while disabling all other mods, and that did not work.

I also manually edited Route 1 encounters in a separate mod to see if the issue was from filling in the empty encounter slots. I set all of the original encounters to be different pokemon, and route was unaffected.

**Comment by kwsch** [comment]
If the installed patch is overriding any of the data, then it uses the installed patch rather than the layeredfs copy.

Data doesn't magically un-randomize during runtime.
