### ISSUE TITLE
Randomizing Starters in PLA

### ISSUE THREAD

**Issue by Drageto** [kwsch/pkNX#191]
So I can randomize the wild pokemon fine, but randomizing starters just constantly makes them end up as eggs which hard locks your progression. Maybe I can hatch them?

**Comment by kwsch** [comment]
You can't hatch them.

Delete everything except for resident.gfpak in the dumped folders; it seems that some data like Personal/Learnsets/Evolutions isn't being serialized back to data correctly.

**Comment by Drageto** [comment]
So randomizing statics is weird, the first time I randomized the alpha kriketune it turned into alpha machamp, the 2nd time it turned into a shiny lucario that was level 0 and had an egg icon. Battle ended immediately.
