### ISSUE TITLE
PLA randomizer Legends True Not working

### ISSUE THREAD

**Issue by Drageto** [kwsch/pkNX#195]
Mythicals/Events work perfectly fine when randomizing, but when I try to set Legends to true everytime it keeps resetting after I save and it doesn't randomize them. The pokemon that aren't being randomized are giratina, dialga, palkia, the genies, lake trio and heatran, but the mythicals like darkrai and manaphy work perfectly fine. The legends setting worked on previous builds it seems to have broken with the recent updates.

It also isn't saving the actual legends true/false setting. So like when randomizing by bst, events, legends, typing all the other save my preferences but legends keeps resetting whenever I save it, it always resets back to false. So if I set event mythics to true, save the randomization and open it back up it'll still be on true, but this doesn't happen with legends.

**Comment by kwsch** [comment]
It's hardcoded to be disabled because legendaries in the wild breaks the game progression.

**Comment by Drageto** [comment]
when is the progression broken? I was able to previously get past the third area without any issues

**Comment by kwsch** [comment]
Breaks the legendary specific quests.

**Comment by Drageto** [comment]
Oh that's so unfortunate, do you think there's anyway to work around that? Would randomizing the game with legends and then when you get to specific quest doing another randomization of it without them work? So you could have them for all the main story up until then

**Comment by kwsch** [comment]
No, because the act of encountering and capturing the legends prior to the quest causes savedata values to be set that interfere with the quest.

pkNX is safeguarding the player from breaking the save file, with this restriction it's a fair trade off.

**Comment by Drageto** [comment]
Oh so catching them early breaks the game, man that sucks. Oh well.
