### ISSUE TITLE
PKNX gives missing DLL Error when trying to open spawn tab in PLA

### ISSUE THREAD

**Issue by H3roDude** [kwsch/pkNX#196]
Im using the latest artifact of Pknx but it tells me that the DLL oo2core_8_win64 is missing. I dumped the Game multiplie times but i dont know how or where to get that file. I searched fo the file on google and found a download link but when i open the tab again it just gives me a blank page
![image](https://user-images.githubusercontent.com/28226801/156918867-bd13c0a2-3a10-40a8-9910-6d25e61f6869.png)

**Comment by sora10pls** [comment]
Working as intended.

DLL error: Oodle is required to use the spawn editor.
No images: map textures are to be dumped from your ROM and placed into a `map_pla` directory next to the exe.

**Comment by H3roDude** [comment]
SO i placed the Map texture files into a new directory called map_pla but it still gives me this blank window
![image](https://user-images.githubusercontent.com/28226801/156939511-f726543a-3979-4246-a6cd-510798ca3b7c.png)
![image](https://user-images.githubusercontent.com/28226801/156939520-b08be5f3-a1bc-47dc-a1b4-6fea70d3f6bd.png)

**Comment by H3roDude** [comment]
Also tried only putting the files from map_texture into the map_pla dir with no luck

**Comment by kwsch** [comment]
It's expecting the .png files directly in the folder.

Keep in mind the Spawns GUI window is just for data visualization, and doesn't actually edit anything.

**Comment by H3roDude** [comment]
oh okay, thank you!

**Comment by kwsch** [comment]
There's another editor that allows you to randomize wild content ;)

**Comment by H3roDude** [comment]
i guess its the section "Areas" ? I randomized them but its still spawning bidoof and Starly for me. Is the Obsidian Grasfields ha_area00 or area01?

**Comment by MegaKBang** [comment]
You have to randomize every area seperately to have it really randomized

**Comment by H3roDude** [comment]
i randomized pretty much ha_terrain_workflow_test_01 till ha_area11 but i'll just scrap it and try it again with all area sections. Thank you

**Comment by H3roDude** [comment]
So i randomized every area there is and its still default spawns :/

**Comment by H3roDude** [comment]
i found the issue, mods were interfering with the randomizer
