### ISSUE TITLE
SwSh Randomization Feature Request

### ISSUE THREAD

**Issue by RevanXVIV** [kwsch/pkNX#199]
Would it be possible to add an option to modify shiny odds for Sword and Shield like it is for Let's Go? I prefer quicker hunts and that would really help out a lot.

EDIT: Changed the topic from a question to a request.

**Comment by pantsman0** [comment]
@RevanXVIV I just submitted a PR, can you give it a test on your game dump?

**Comment by kwsch** [comment]
Closed by #211
