### ISSUE TITLE
Mod appears as "partial" when applied through SimpleModManager

### ISSUE THREAD

**Issue by georges9936** [kwsch/pkNX#208]
I'm not tech-savvy at all, so sorry if this is a dumb mistake on my behalf. I'm using an actual switch with atmosphere, not yuzu.

Basically I randomized LPA just fine with PKNX, created the mod and moved it in the right folder on my switch's SD. I then boot up my switch under Atmosphere and open up SimpleModManager in order to actually apply the mod to the game. The mod shows up in the list just fine, but when I try to apply it, it shows up as "partial (7/8)" and when I boot the game, it's not randomized. Does anyone know what I might be doing wrong ?

**Comment by kwsch** [comment]
Unrelated, you may have to investigate the mod manager's logs or documentation.
