### ISSUE TITLE
AI flags + My own research on what the Unused flag does.

### ISSUE THREAD

**Issue by DioVento** [kwsch/pkNX#21]
Hi! I've got some questions about the AI tags in PKNX. Do you have any information on what the Basic, Strong, Expert, and Allowance flags do?

Also, the Unused flag is actually used on a couple of Trainers, it appears to be related to the fire Gym Challenge where you're "competing against" the partner in a Multi Battle.

**Comment by kwsch** [comment]
Refer to the amx scripts in the battle ai folder.

They've rearranged the flags and added a few more since lgpe; the GUI needs an update to show more flags.

**Comment by pratmangalore** [comment]
Hi. I had a question regarding this topic. How do I open and modify these amx scripts?

**Comment by sora10pls** [comment]
Further documentation:
```
Bit 01: Basic
Bit 02: Strong
Bit 03: Expert
Bit 04: Double
Bit 05: Raid
Bit 06: Allowance
Bit 07: Unused
Bit 08: Motostoke Gym Trainer
Bit 09: Motostoke Gym Trainer
Bit 10: Unused
Bit 11: Item
Bit 12: Motostoke Gym Trainer
Bit 13: Unused
```
Not sure what the Gym Trainer flags even do, but...

Gym Trainers that have 4 Poké Balls
* Bits 8 and 12 set
* Bit 9 not set

Gym Trainers that do not have 4 Poké Balls
* Bit 9 set
* Bits 8 and 12 not set
