### ISSUE TITLE
Compiling on Windows 11

### ISSUE THREAD

**Issue by droidforever** [kwsch/pkNX#212]
When i try to build the solution I get this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.	pkNX.Sprites	C:\Program Files\dotnet\sdk\5.0.409\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	141	
I have no idea how to fix this I am a noob at Visual Studio 19

**Comment by kwsch** [comment]
Google it.

https://www.google.com/search?q=Error+NETSDK1045+The+current+.NET+SDK+does+not+support+targeting+.NET+6.0.+Either+target+.NET+5.0+or+lower%2C+or+use+a+version+of+the+.NET+SDK+that+supports+.NET+6.0.
