### ISSUE TITLE
Unable to open rom files

### ISSUE THREAD

**Issue by Kyubay20482** [kwsch/pkNX#213]
when i to open the rom files it says this
![error opening](https://user-images.githubusercontent.com/109465912/179397716-6f01c8b7-e6d5-43be-808c-ff9de8ba7ee5.PNG)

**Comment by kwsch** [comment]
The program opens folders containing dumped ROM data.

Ensure you have properly dumped and unpacked the ROM data, and that the folder is not stored on a cloud folder like OneDrive. The files need to be located on your hard drive.
