### ISSUE TITLE
Having trouple finding which folder to open in pknx

### ISSUE THREAD

**Issue by Kyubay20482** [kwsch/pkNX#214]
i have my dumped romfs and exefs in my hard drive and in its own seperate folder and no matter which folder i open it has errors
![Capture](https://user-images.githubusercontent.com/109465912/179403364-7a284244-b487-4d19-b44e-6c493671e387.PNG)
![when i open the romfs file](https://user-images.githubusercontent.com/109465912/179403365-c994e226-4629-4ceb-bbed-41d88c7e74cb.PNG)
![when i open the whole dumped game folder](https://user-images.githubusercontent.com/109465912/179403367-bdb82ad2-a1be-4d01-aded-d4e00315901c.PNG)
 so how do i get my romfs folder ready to use in pknx?

**Comment by sora10pls** [comment]
Please stop opening issues after you’ve already had your last, for the same topic, closed with an answer.

pkNX expects one folder that contains folders that begin with `rom` and `exe` for RomFS and ExeFS, respectively.

Rename that v458752 folder to `romfs`. If your dump is Sword Ver. 1.3.2, pkNX will load your game dump.
