### ISSUE TITLE
Wild encounters unaffected after randomization

### ISSUE THREAD

**Issue by xToyoko** [kwsch/pkNX#215]
Hey,
I'm running into an issue and after hours of trying to fix it, I'm getting pretty frustrated. There's no fix to be found ANYWHERE on the internet, and I also didn't find anything here.
Basically, I followed every step very carefully. I randomized static encounters, wild encounters, abilities, movesets and trainers. After installing the modded folder, I started the game to see if it worked. And, yes, everything works - Except for wild encounters. On every single route and part of the wild area, the wild encounters are completely unaffected. They still have random moves and abilities, but they are the same species as before, and nothing I do changes that. Statics work fine, wilds dont work at all.

I've tried using an older release of pkNX (currently on the latest build), to no success. I also tried to go from 1.3.2 to 1.3.0 - Also didn't help. I'm currently on 1.3.0, but I can change back any time.

The funny part is that every time I re-enter pkNX and go into the Wild tab, it shows me that everything should be randomized just fine. But it doesn't show up like that in-game at all. Is there something I'm doing wrong?

Other mods work fine, it's only the wild encounters. Disabling all my mods and only editing wild encounters doesn't work either.

![Wild](https://user-images.githubusercontent.com/109682587/180027401-ed293470-4837-4677-96b9-5071e08227df.jpg)
![Wild 2](https://user-images.githubusercontent.com/109682587/180027413-25eb170d-4bb9-48cf-9a76-b1c4b459e845.jpg)
![Static](https://user-images.githubusercontent.com/109682587/180027428-bd6c40cc-f117-41fd-88a6-be597b5033f8.jpg)
![failed wildencounters](https://user-images.githubusercontent.com/109682587/180027438-61f0d5e3-786a-4312-a1f8-475b913e837e.jpg)

**Comment by kwsch** [comment]
If the files are correctly loaded by the console, then there's no way for data to magically revert to something that doesn't exist.

Ensure your layeredfs folder is being properly loaded by atmosphere, and that your game ID code (folder name?) is correct.

Tagging @sora10pls if he has anything else to chip in, but this isn't a pkNX issue.

**Comment by xToyoko** [comment]
I kind of have to disagree, as the exact same is also happening to 2 people I know currently. We can't get it to work. I've also tried it with 2 emulators, Yuzu and Ryujinx. THere, it should be as easy as dropping the folder into the mods location, as shown by the fact that I have the same results: Gifts, Statics, Abilities etc get randomized, but wild encounters won't. I also went to see if it might be a savefile issue by creating a new one, and I found that the slumbering woods at the start of the game actually has randomized encounters, but I figure those might count as static as again, not a single wild encounter is randomized.

However, I found out that if I don't add a main file into an exefs before opening pkNX, it saves the edited folder correctly, as "0100ABF008968000". Whenever I do have a main file added, it saves the folder incorrectly, as "02B00972E9B9E717".

Again, if this was the issue for the switch, it'd make sense - But it isn't. Renaming the folder didn't change anything, and on the emulators, the folders name doesn't even matter at all.

What I tried next was uninstalling the DLC files before dumping again, but that also didn't change a single thing. However, if I download a randomized folder by someone who did it for me, and insert it via whatever name I want, everything works perfectly fine - but I badly need to randomize my stuff over and over again, so downloading pre-randomized files isn't an option for me.

At this rate, I'm fairly convinced it's a pkNX issue, as it seems to be working fine if I use a file by someone who did it years ago, but we can't get it to work with 3 switches and 2 emulators on each of our PC's. And, again, only the wild encounters won't randomize. Literally everything else works perfectly fine, and we're completely out of ideas to fix this. And yes, the layeredfs folder IS being loaded properly - otherwise all the other randomizations wouldn't work.

**Comment by sora10pls** [comment]
What version of the game are you loading into pkNX? Sword or Shield?

**Comment by xToyoko** [comment]
Hey, here's the step by step procedure you asked for:
Dumped pokemon sword, ver. 1.0.0. Patched it up to 1.3.2 first, installed the DLCs, and used the latest pkNX. Located the dumped folder in pkNX, started randomizing basically everything that has a randomize button (excluding scripts and texts and such things).First edited pokemon data, then trainers, then statics, then wild encounters, then gifts. At times, even only wild encounters. Clicked on file -> exit to create the patched folder. As it's easier and faster to test that over and over again, I'm currently trying to get it to run on Yuzu first, before going back to my switch. In yuzu, i just throw the patched folder into the mods folder, as that's what you're supposed to do. Everything randomized perfectly, wild encounters didnt. So, I tried to randomize it again, and realize that inside of pkNX, it shows randomized routes and all that, but it wont show up. So, I re-tried anyway - Nothing. Installed the 1.3.0 patch instead, re-dumped the file, still nothing. Downloaded the pkNX release prior to the latest one and tried it with both, 1.3.0 and 1.3.2, nothing. Completely deleted everything, dumped the file again, updated it without installing DLCs, used a new safe file - nothing. My wild-tab looks exactly like yours (with different pokemon of course), but it won't work ingame - Neither for me, nor for my friends.

To the alst part: I compeltely deleted all mods and tried it again, because I thought something might be causing issues as well. But still, to no avail. Also, when I open the program, it only says "Wild", and not "Wild_SW" or "Wild_SH" or anything. So, I'm guessing it should take the right version since I literally located the dumped sword version and loaded it into pkNX. Funnily enough, I said that the randomization works fine if I use a pre-randomized file from the internet, known as extreme randomizer. So, I already tried to take the data_table.gfpak out of this folder, in which everything worked but I cant edit it, and threw it into mine. There, it stopped working again, even tho all I did was taking my not working file out and replaced it with the one that worked.

Do you need pictures of anything? I'd be helpful for any clue you could give me.

**Comment by sora10pls** [comment]
pkNX determines your game version here, depending on if you have ExeFS data present (specifically checks for `main.npdm`). If none exists, it defaults to SWSH (indeterminate), and if it is present, it checks for Title ID, then chooses either SW or SH:
https://github.com/kwsch/pkNX/blob/8da0a5d3d84a3cb655dc2a6b4ebb31ef3faf5ce7/pkNX.Game/GameLocation.cs#L108-L116

From there, opening the wild editor will then choose the appropriate wild data to edit, depending on game version. If indeterminate (no ExeFS data present), the user is prompted to choose which version:
https://github.com/kwsch/pkNX/blob/8da0a5d3d84a3cb655dc2a6b4ebb31ef3faf5ce7/pkNX.WinForms/MainEditor/EditorSWSH.cs#L193-L206

I now believe that the issue is pkNX sees that your Title ID is not 0100ABF008968000 (expected for Sword), but rather 02B00972E9B9E717, which is not a valid Title ID. This then makes pkNX default to editing Shield encounters, rather than Sword encounters.

I’ve tried ExeFS dumps of my own from 1.0.0, as well as 1.3.0, 1.3.1, and 1.3.2, and to no avail can I replicate your issue. The issue lies in your ExeFS, and pkNX assuming that it should be editing Shield encounters.

I can look into revising the logic later today.

**Comment by xToyoko** [comment]
Alright, thank you. I should've stated tho: I tried it without main.npdm file already, and it showed exactly what you said. It switched to the right folger name after randomizing, as I said while opening the post. But, picking the sword option manually, while it fixed the folder name, didn't change the issue. It's still not randomized. I'll try to see if theres something wrong with my gamefiles later by forcefully editing it as shield file, and see what happens then. I appreciate the help!

**Comment by sora10pls** [comment]
The two commits I just pushed should fix these issues. If pkNX can't grab a valid Title ID from your ExeFS data dump, it will now recognize the game as SWSH (not SW or SH, specifically), and the wild editor should prompt you for version selection upon clicking it.
