### ISSUE TITLE
Unable to edit pokemon

### ISSUE THREAD

**Issue by grannyd15** [kwsch/pkNX#221]
When I click the "Pokemon" button to try to edit the pokemon it shows the error message 
"Index was outside the bounds of the array.
at pkNX.Structures. PersonalTable.GetFormList(String[] species, Int32 MaxSpecies) at pkNX.WinForms.PokeDataUl..ctor(PokeEditor editor, GameManager rom, GameData data) at pkNX.WinForms.Controls. EditorSWSH.EditPokémon()"

**Comment by kwsch** [comment]
Per the readme:

> For Sword and Shield, pkNX operates under the assumption that your dumped ROM includes the Ver. 1.3.0 patch.

The base ROM's data structures were revised by patches. pkNX doesn't cater to the base ROM structures, it wants the latest revisions from 1.3.0. So, dump the patch content and merge the two romfs/exefs folders. Once you do that you'll be able to edit the game data.

**Comment by grannyd15** [comment]
When i try to load the data in 1.3.0 it dosnt allow me to even open it
