### ISSUE TITLE
Move editor 

### ISSUE THREAD

**Issue by TUMTUMTARAM** [kwsch/pkNX#224]
What move quality means?
Theres a database to see what each number mean? Like in Types and Effect

**Comment by kwsch** [comment]
You can dump the entire array of moves to text, then look at it in a spreadsheet editor.

Referring to pk3DS's list of "qualities":

```
"Only DMG",
"No DMG -> Inflict Status",
"No DMG -> -Target/+User Stat",
"No DMG | Heal User",
"DMG | Inflict Status",
"No DMG | STATUS | +Target Stat",
"DMG | -Target Stat",
"DMG | +User Stat",
"DMG | Absorbs DMG",
"One-Hit KO",
"Affects Whole Field",
"Affect One Side of the Field",
"Forces Target to Switch",
"Unique Effect"
```

It's not well documented what each quality value means in each game.
