### ISSUE TITLE
[SH] Randomize Learn: 'Index was outside the bounds of the array.'

### ISSUE THREAD

**Issue by Pib0** [kwsch/pkNX#23]
Comes up when pressing the Randomize button under the Randomize Learn tab in the Pokémon Editor. This is on a clean rip of the game files. Everything is completely untouched.

Full details:
https://pastebin.com/GagCZM60

Linking to pastebin because posting something that tall makes me feel like I'm spamming.

**Comment by nielsyboy765** [comment]
I have the same problem

**Comment by SnakeDeath** [comment]
![image](https://user-images.githubusercontent.com/25617671/70367669-23f9af80-18b3-11ea-964c-538b4b8c1ba6.png)
same problem right?

**Comment by kwsch** [comment]
Probably because MoveData isn't loaded (empty array).

Loading MoveData will probably be slow since it's 800+ flatbuffers to be converted via the flatc compiler...

Maybe I can just generate a throwaway flatbuffer reader class -> json -> movedata to be faster.

**Comment by SnakeDeath** [comment]
the trainers randomaizer and the randomize learn in pokemon editor , both have same issue i believe

**Comment by DarkShinyGiratina** [comment]
Yeah, randomizing the trainers leads to the same error, and also (unrelated) can generate mons not in the game.

**Comment by SnakeDeath** [comment]
@kwsch sorry to ask but any update about this issue?
