### ISSUE TITLE
Editing VAR values

### ISSUE THREAD

**Issue by motoxfreak207** [kwsch/pkNX#230]
Mostly its just a question because I haven't been able to find an answer anywhere. I have edited the starters in sword and changed the appropriate static encounters, trainers teams, etc. However, I can't figure out how to find and edit the options available for VAR values in Scripts and Common. I have tried everything I can think of and looked everywhere I can think of for an answer to no avail. Any assistance in pointing me in the right direction would be very much appreciated as I have hit a dead end. Screenshots included.
![Screenshot 2022-09-11 203049](https://user-images.githubusercontent.com/76827052/189757771-0e712b31-470a-401b-b2d1-9e659727f18d.jpg)
![Screenshot 2022-09-11 203127](https://user-images.githubusercontent.com/76827052/189757781-45e08a5a-6887-4a03-8c95-db9a8e2b4dbd.jpg)
![Screenshot 2022-09-11 203248](https://user-images.githubusercontent.com/76827052/189757810-7296ae87-f21a-40da-a74a-dc360dae5676.jpg)
![Screenshot 2022-09-11 203420](https://user-images.githubusercontent.com/76827052/189757822-0e81cd96-7a94-434a-ae64-8411dbdd62ee.jpg)
![Screenshot 2022-09-11 203448](https://user-images.githubusercontent.com/76827052/189757831-4ca21b83-4e18-42ff-955a-da7d0675147b.jpg)

**Comment by kwsch** [comment]
Nobody took the time to document what each var code is for SW/SH

**Comment by motoxfreak207** [comment]
So there is currently no way to change what is displayed by the var script?

**Comment by kwsch** [comment]
There is no table for SW/SH. Someone would have to create the new table and label each var code they want to be recognized.

https://github.com/kwsch/pkNX/blob/86cf8027ca70ad4c0a4a528491a50812bdf7f920/pkNX.Structures/Text/TextVariableCode.cs#L16-L31

**Comment by motoxfreak207** [comment]
Would that be hard to do? and if it's not hard but just tedious, would that be something that can be added to pknx via c#? i dont mind learning if it can be done but i dont know where i would start

**Comment by kwsch** [comment]
download github desktop

fork the pkNX repo to your own account so you can make changes

Install Visual Studio Community Edition

Install .NET Framework SDK

Open the sln, Build->Rebuild All

Edit the linked cs file shown above, to do something similar as the other games

Add a new line for each text var code alias that should be shown instead of the raw ID

build program and run, verify changes were made

make a new commit

make a new pull request for that commit
