### ISSUE TITLE
Update to netstandard2.1

### ISSUE THREAD

**Issue by JelleInfinity** [kwsch/pkNX#233]
It seems mono does support `netstandard2.1` (See the [docs page](https://docs.microsoft.com/en-us/dotnet/standard/whats-new/whats-new-in-dotnet-standard?tabs=csharp#supported-net-implementations), it mentions mono 6.4+).
Would love to update to this version to add support for default interface implementation.

@kwsch Could you confirm `netstandard2.1` works ?

**Comment by JelleInfinity** [comment]
Actually nevermind, it seems winforms is not supported by `netstandard2.1`.

How would you feel about using WPF instead of winforms? WPF seems to be cross-platform as of 2022

**Comment by kwsch** [comment]
netstandard2.1 is not supported by the .net framework

I'm fine with upgrading to net6 (net7 when GA and azure build agents support it) across the pkNX project. PKHeX is the only one I'm really hesitant, as I'd like to add initial SV support for net46 prior to forcing all >100k users to install the net6+ runtime.
