### ISSUE TITLE
[Trainer Editor] Number of Pokemon in party not randomizing

### ISSUE THREAD

**Issue by DeathChaos25** [kwsch/pkNX#24]
So I tried using [this exact combination of settings](https://cdn.discordapp.com/attachments/637746288057778186/645765755496824843/unknown.png) to randomize trainer Pokemon in Shield (while still keeping the original Pokemon), basically, I want the randomizer to add extra Pokemon to their party while keeping the existing ones.  

Instead of randomizing the number of Pokemon in the party, it's simply bumping them to the required minimum and not adding any more, so if I set min to 3 and max 6, everyone who had less than 3 now has 3, but never 4-5-6, if I set the min to 2, everyone who had 1 now has 2, but never 3-4-5-6, etc.

Hope my explanation is clear enough.

**Comment by kwsch** [comment]
That's the intended behavior; it pulls everyone up to the minimum required count, and drags everyone down to the maximum.

```
if (count < min)
    count = min;
else if (count > max)
    count = max;
```
