### ISSUE TITLE
How do SwSh increased shiny odds work?

### ISSUE THREAD

**Issue by RevanXVIV** [kwsch/pkNX#240]
Ok so is this like what PK3DS does for gens 6 and 7 or does this only affect certain wild pokemon? I've been running around with encounters for a while now at 1.17% shiny odds and nothing.

**Comment by kwsch** [comment]
It works; test it by setting it much higher. Be sure that you don't have conflicting mods/patches overwriting your changes.

Keep in mind that the overworld does not show it as shiny until you encounter it in battle.
