### ISSUE TITLE
Changes don't show at all (Sw/Sh)

### ISSUE THREAD

**Issue by Alexowo** [kwsch/pkNX#27]
I modified bin/pml/evolution/evo_831.bin and copied the folder that pkNX created (0100ABF008968000/RomFs etc) to my SD Card at atmosphere/titles and restarted my Switch. When I go into the game the things I've changed don't show up at all (for example Wooloo isn't evolving into Magikarp at Level 6) plus I used someone else's mod (title screen logo swap) and that didn't show up either. If this is an issue with LayeredFS, could I know what I'm doing incorrectly?

**Comment by kwsch** [comment]
The files are modified successfully; you have an issue with loading them, which is unrelated to pkNX.

**Comment by Alexowo** [comment]
Hmm, thanks
