### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by Jmc1922** [kwsch/pkNX#273]
I downloaded the newest version of pknx along with .net 6.0.0 but app isn’t launching is there anything else I need to do for it to work?

**Comment by JelleInfinity** [comment]
Does it give you any errors?

**Comment by Jmc1922** [comment]
Not after I installed the requested dot net download, now when I click to run PKNX nothing happens , nothing gets loaded at all

**Comment by JelleInfinity** [comment]
Okay, might be a bug in the code I just pushed. I'll have a look

**Comment by JelleInfinity** [comment]
Doesn't seem to be my code. What OS are us using?

**Comment by Jmc1922** [comment]
Windows 10

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jmc1922** [comment]
And found the latest version on the projectpokemon website the link sent me to the pipeline where I downloaded it from

**Comment by JelleInfinity** [comment]
I've just pushed a change that will make sure the window has some size when it opens. Once the build is ready, please try that one :)

**Comment by Jmc1922** [comment]
Now it’s saying “Microsoft.NETcore.app” version 6.0.0 was not found I’m gonna try find that and re download it to see if it works

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
