### ISSUE TITLE
Blank Pokémon Names For Pokémon Shield (In-Game)

### ISSUE THREAD

**Issue by RuinousPrincess** [kwsch/pkNX#281]
I have no idea what is going on my end, but for some reason when randomizing Pokémon Shield for Yuzu, Pokémon names are blank in-game alongside having Japanese text on the upper-right by the gender. Even when Hop sends out his Pokémon it says "Hop sent out..." no name. Pokémon Sword has no issues, but Shield is just acting rather weird for me. Both got DLC and are version 1.3.0. 
![No name](https://user-images.githubusercontent.com/83746056/196024606-7fc29495-95a0-4883-8801-716e4e96ab2c.PNG)

**Comment by kwsch** [comment]
Double check that the Common text names for species (mons?) has the original data.

pkNX isn't changing this data when you randomize, so not sure what went wrong for you. Can always delete the edited text files so layeredFS doesn't load the bad text files.

**Comment by RuinousPrincess** [comment]
That's the thing, I never randomized Common text for Shield, all I did was edit moves/Pokémon stats/Trainer Pokémon, that's about it and this happened. I've done the same for Sword, no issue with it. No matter what I do, it's still displaying blank names or Japanese text. I'm really confused on why Shield is behaving so abnormal with PKNX for me.
![Capture](https://user-images.githubusercontent.com/83746056/196064605-930643f8-a83e-45fa-8130-1d8578164545.PNG)

**Comment by kwsch** [comment]
Is there anything in your layeredfs folder for Common? Might be a 0-byte file that the game aborts reading, returning empty strings because the file has no data.

**Comment by RuinousPrincess** [comment]
Nope, no Common stuff. There's a pml folder with a evolution, personal and waza folder. Inside of the trainer folder is just the trainer data and trainer poke data. That's it, I don't see anything for Common period for me.

**Comment by kwsch** [comment]
Try deleting individual layeredfs files until the issue goes away. Not sure what the root cause is otherwise.

**Comment by RuinousPrincess** [comment]
I finally found the problem. Apparently, PKNX appears to be just fine, as I found out the Cheat Codes I was using appears to break the game that names don't appear yet disabling them fixed the game. Seems like the Shiny code was broken, so removing it fixed the game.
