### ISSUE TITLE
Dump Table in Pokemon Editor giving an error message

### ISSUE THREAD

**Issue by ArcByte** [kwsch/pkNX#282]
So I've been learning to randomize pokemon sword and shield for the past day and got everything working in terms of actually randomizing but I was interested to look at all the info for the pokemon I randomized. When I pressed the "dump table" button at the bottom of the menu I'm greeted by an error message saying unhandled exception has occurred. Of course I am able to continue with using the randomizer as usual if I press continue on the pop up but I don't get any file or clipboard copy paste to put into a spreadsheet.
[Error Message Details.txt](https://github.com/kwsch/pkNX/files/9843583/Error.Message.Details.txt)

**Comment by kwsch** [comment]
notes: reflection with span property getter
