### ISSUE TITLE
i have a problem 

### ISSUE THREAD

**Issue by ilai15** [kwsch/pkNX#285]
i want to increase shiny odds pokemon shild, but i dont success

**Comment by ilai15** [comment]
![WhatsApp Image 2022-10-19 at 04 06 38](https://user-images.githubusercontent.com/64400589/197366305-3195fdb0-2aef-447a-a1f0-2289759808d7.jpeg)
and when i change the main in to npdm it says 
![WhatsApp Image 2022-10-19 at 03 36 18](https://user-images.githubusercontent.com/64400589/197366332-ce984dca-bade-4543-8d85-453ff374f022.jpeg)

**Comment by kwsch** [comment]
Too vague. 

Use the program, and double check the settings you put are being loaded by the game. Try an obscenely high reroll count to confirm your changes are being recognized.

**Comment by ilai15** [comment]
when i don't change main into npdm it says 
![d9e22c6c-6c1f-431a-838f-bb2713caddbd](https://user-images.githubusercontent.com/64400589/197366352-ceb81bae-826c-4f95-8934-9d387630098f.jpg)
and when i chnge the main in to npdm it says 
![fe2c517e-94c0-45eb-ab8f-cd87de2d09d7](https://user-images.githubusercontent.com/64400589/197366362-dcd88aad-e027-439b-a6da-5fc9d074d4f4.jpg)

**Comment by kwsch** [comment]
Dump your exefs completely with whatever tool. You should have both `main.npdm` AND `main` as separate files.
![image](https://user-images.githubusercontent.com/6393368/197367187-31f77c15-9b08-4974-8935-98a6ac4db0f8.png)

**Comment by ilai15** [comment]
i have yuzu and the files i have is main and backup

**Comment by ilai15** [comment]
![e496bcd4-4e57-46b1-ac1e-486601f456f4](https://user-images.githubusercontent.com/64400589/197368683-4da230a9-cfaa-4eff-8552-29d1ae5d33ea.jpg)

**Comment by kwsch** [comment]
Those are save files.

Dump the ROM from with your Nintendo Switch.

**Comment by ilai15** [comment]
i dont have nintendo switch, i need this to  increase shiny odds or there is another way?
