### ISSUE TITLE
farmharvest.dat generation issue

### ISSUE THREAD

**Issue by elayes211** [kwsch/pkNX#287]
Hello! The generation of farmharvest.dat, when I modify the text from within the pkNX, seems bugged to me.

I will provide information here, the text is changing places and some of the text is empty, ingame.

**Comment by elayes211** [comment]
Yes, the number of new lines are different!

**Comment by elayes211** [comment]
Same is happening with the icho_rare_shop.dat
Same scenario I think, misplaced texts

**Comment by duckdoom4** [comment]
Could you tell us what game this was for?
