### ISSUE TITLE
I need help with pkNx and quite fast cause i wanna play it

### ISSUE THREAD

**Issue by Aizen232** [kwsch/pkNX#288]
So ill try to go in detail but my problem is that whenever i try to open the pokemon shield i downloaded in pkNX it says (Failed to initialize ROM data please ensure your drump is correctly set up, with updated patches merged in (if applicable) Index was outside the bounds of the array) i could play the game on yuzu no problem but i cant randomize it or anything

**Comment by JelleInfinity** [comment]
Could you include a screenshot of the error? That could help us identify the issue

**Comment by Christianwidjaya** [comment]
Troubleshooting steps
1. Make sure you are dumping both basegame and update properly. Use hactool and basenca properly.
2. You have to attain RomFS file count magic number of 50494, no more, no less. If you have more from the target, you have to delete a few data that you wouldn't use/mod to attain that number (suggested outside of bin). If you have less, then you should redump the data again, you definitely doing it wrong.
3: If you dumped DLC files, you are doing it wrong. You have to dump both basegame, then update package with baseNCA of the basegame. If you failed to do so, then that's your problem.
4: Last, target "extract" folder where you hold both exefs and romfs, not common folder.

If these doesn't work, then you should reply here

**Comment by JelleInfinity** [comment]
Closing this issues because of lack of communication
