### ISSUE TITLE
Sword and shield- the personal screen is too big

### ISSUE THREAD

**Issue by Jmc1922** [kwsch/pkNX#289]
I’m trying to edit sword and shield personal table but the screen is too big and it won’t let me minimise it

**Comment by kwsch** [comment]
Use a bigger monitor.

**Comment by Jmc1922** [comment]
It’s only really recently , it’s never been an issue before the recent updates

**Comment by kwsch** [comment]
The program has been updated to use .NET6 which respects the DPI sensitivity of the computer to have larger forms.

Small monitors don't play nice with large forms; maybe the forms can be redesigned to be more tabular, but it is what it is.

**Comment by JelleInfinity** [comment]
You can try to mess with your dpi scaling settings. Eg. set it to 75%, which would make your display look bigger then it is.

Honestly not sure if windows allows this on small screens..

**Comment by JelleInfinity** [comment]
Also, what's the 'personal screen'? Screenshots would help us identify the editor you're referring to.
