### ISSUE TITLE
cannot load dump file

### ISSUE THREAD

**Issue by TheLaggs** [kwsch/pkNX#290]
I have pokemon brilliant diamond fully updated and whenever I dumb the game using yuzu/ryujinx whenever I load the folder I always get the error "an error occurred while loading the game files. Couldn't infer game version from romfs file count. your game dump might have been corrupted". I have 0 clue how to fix it I've followed all the tutorials on yt/anywhere and nothing fixes it. I don't know if yuzu or ryu is the problem or if the form I downloaded is the problem any help would be appreciated

**Comment by kwsch** [comment]
Per the readme's feature list:
https://github.com/kwsch/pkNX#features

This program does not support Brilliant Diamond / Shining Pearl.
