### ISSUE TITLE
Error trying to use pknx for Pokémon scarlet

### ISSUE THREAD

**Issue by Jmc1922** [kwsch/pkNX#291]
I’m trying to set up pknx for scarlet , I’m using fat32 (which splits files more than 4gb) and whenever I try to load pknx I keep getting this error
![image](https://user-images.githubusercontent.com/115006410/204103290-e7196184-652e-49a1-8b21-b80c92138bf8.jpg)

**Comment by JelleInfinity** [comment]
Sc/Vi are not yet supported
