### ISSUE TITLE
"pknx.winforms.subforms.mapviewer9.resources" not found

### ISSUE THREAD

**Issue by Queryw** [kwsch/pkNX#296]
[https://imgur.com/a/AfMNvFc](url)
![Screenshot 2022-12-09 132719](https://user-images.githubusercontent.com/120212653/206769378-5d4a1d19-d946-43ee-b36b-0db7e31cc5f8.png)

**Comment by JelleInfinity** [comment]
We can't redistribute Nintendo's property with pkNX. Because of this, these files have been excluded from the public release. 

I'm not sure if there's a way around this currently, like there is in the PLA version of pkNX. We'd need to update the code to look for these files inside of a folder provided by the user

**Comment by JelleInfinity** [comment]
After a quick look at the code, it seems you can add the map image in the following location: "map_sv\paldea.png"

**Comment by Juno87** [comment]
> After a quick look at the code, it seems you can add the map image in the following location: "map_sv\paldea.png"

Hi, thanks for this reply. Can you elaborate on this a bit? Should we create a folder with the paldea map and compile pknx again or...? Sorry I'm a total noob at this, so not sure if that was a stupid question.

**Comment by kwsch** [comment]
> > After a quick look at the code, it seems you can add the map image in the following location: "map_sv\paldea.png"
> 
> Hi, thanks for this reply. Can you elaborate on this a bit? Should we create a folder with the paldea map and compile pknx ourselves or...? Sorry I'm a total noob at this, so not sure if that was a stupid question.

No, you just need a folder next to the `exe`, as listed above, with the map image inside of it. It's the same as PLA.

It doesn't edit anything at this time. It's just for data visualization to help with datamining.
