### ISSUE TITLE
tprfs data denied

### ISSUE THREAD

**Issue by Kyubay20482** [kwsch/pkNX#297]
i am getting an error when i try to open my folder it keeps saying that my trpfs data is denied for scarlet and violet

error is 

desktop/0100A3D008C5C000/romfs/arc/data.
'trpfs' is denied

![pknx scarlet error](https://user-images.githubusercontent.com/109465912/206804211-28d3265c-29f0-47ad-8984-3572c71f2cb9.PNG)

**Comment by Juno87** [comment]
It's because when you dumped your  game you set it to accommodate fat32 file size so it split data.trpfs into two files. I had to turn that off and dump the game again to get one file instead of a split file and dump the game again.

**Comment by kwsch** [comment]
The program needs to read the specific files. These files need to be stored on the local machine, not in a OneDrive folder or locked by another program.

Ensure your ROM is dumped correctly, and all the files are available to the operating system.

**Comment by Jmc1922** [comment]
> For me, it was because when I dumped my game I set it to accommodate fat32 file size in nxdumptool so it split data.trpfs into two files. I had to turn that off and dump the game again to get one file instead of a split file.

How did you turn it off sorry because it won’t let me dump the romfs if it is off because the file is too big
