### ISSUE TITLE
S/V issue

### ISSUE THREAD

**Issue by Jmc1922** [kwsch/pkNX#298]
It says on the read me that pknx has been updated to work with s/v however I keep on getting error messages

![image](https://user-images.githubusercontent.com/115006410/206808078-bae20f7c-b7d1-4b31-b757-8770067165be.jpg)

**Comment by kwsch** [comment]
>romfs file count

Need to have 25 files (merged base ROM and patches), per the filecount detection logic.

https://github.com/kwsch/pkNX/blob/432a6972e74921c5226247e639085693b6968ad7/pkNX.Game/GameLocation.cs#L91
