### ISSUE TITLE
Enquiry for S/V issues 

### ISSUE THREAD

**Issue by BaiyuanLiu** [kwsch/pkNX#300]
Hi kwsch, 

Thank you for contributing to pkNX, that is amazing work. I have follow your instruction to apply nxdumptool and dump the exefs and romfs two file and keep them in one big file, and when I drag this file at the latest pkNX, it will like the image 1 looks like. Can I ask does this pkNX layout and function are right for the violet game? The image 2 is when I click show field editors - Map viewer. I assume it may have been something wrong during the process, If possible would you let me know how can solve this issue? Thank you for your help! 
![image](https://user-images.githubusercontent.com/94757190/206878322-524a444f-caa0-4945-9505-2c22a7ed386c.png)
![image](https://user-images.githubusercontent.com/94757190/206878354-1107ea25-8d94-4051-ae94-4feb4a05038a.png)

**Comment by JelleInfinity** [comment]
See issue #296
