### ISSUE TITLE
PKNX - error

### ISSUE THREAD

**Issue by LegendClay** [kwsch/pkNX#303]
For some reason, whenever i try to use PKNX and select "master dump" > any of the options, an error pops up as seen in the picture attached below. I did try to fix the issue myself but no luck! any help with this?

![PKNX error](https://user-images.githubusercontent.com/120227513/206921631-722db748-4e8b-41be-b777-c6455e84ecf4.JPG)

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/206926516-1a74946c-d332-4dfd-908a-d6dc9fc3174d.png)
You need the oodle dll, same as for PLA.
