### ISSUE TITLE
Not loading S/V

### ISSUE THREAD

**Issue by Ashiato2** [kwsch/pkNX#304]
I dumped my romfs and the program only expects 25 files? i have 273,886 files. I don't understand what the program is expecting and i'd appreciate some help

**Comment by kwsch** [comment]
The program expects a packed romfs (trpfs/trpfd), not an unpacked one.

**Comment by Ashiato2** [comment]
oh alright, thanks. is there support for trainer editing, i want to make a mod that makes trainers harder.

**Comment by kwsch** [comment]
> oh alright, thanks. is there support for trainer editing, i want to make a mod that makes trainers harder.

No, refer to the readme.

> Scarlet / Violet (Currently only for dumping information, not to edit files!)
