### ISSUE TITLE
Move

### ISSUE THREAD

**Issue by TUMTUMTARAM** [kwsch/pkNX#305]
I change the name of the move in the editor and when I choose it, it appears as I changed it.
But when you use it, it goes back to its original name.
![image](https://user-images.githubusercontent.com/33793274/207860296-bafd206f-55ab-4f40-b2cc-ae75353e2a10.png)
![image](https://user-images.githubusercontent.com/33793274/207860307-f7ee7405-7e23-4871-972c-e78a98d265a3.png)

**Comment by kwsch** [comment]
Move names show up in multiple text files.
