### ISSUE TITLE
Evolution Issues

### ISSUE THREAD

**Issue by Ecroton** [kwsch/pkNX#306]
Trying to edit evolutions manually for Pokemon Shield, and running into issues. Trying to edit evolution methods for trade evolves, particularly Spritzee, Swirlix, Karrablast, and Shelmet. I'm aware there are already mods for this, but I prefer to do it myself. So I finally managed to get Spritzee and Swirlix to work, but only during the daytime, despite having a 2nd option for "EvolveWithHeldItemNight". Can you not have more than 1 option for evolutions, and why no just "EvolveWithHeldItem" option? Karrablast and Shelmet simply will not evolve, no matter what I do. Tried several different methods, including just a standard "LevelUp" at level 35. The original evolution file for them was empty to begin with as well, which I thought was weird. Believe that may have also been the case for Spritzee and Karrablast, but can't 100% recall. Any help would be greatly appreciated. It's likely I'm missing something obvious, as I'm super new to the modding scene. This is actually my first ever project.

**Comment by kwsch** [comment]
Certain species are hardcoded into game logic, and the evolution method is a cosmetic notation by the developer.

The names of evolution methods are the actual evolution methods. You can add more ways to evolve using the pre-existing evolution types, like Feebas->Milotic can evolve via Beauty or Held Item Trade.

https://github.com/kwsch/pkNX/blob/7c804255bc34ed6623ab4a8eaa6ca0f23f33fb84/pkNX.Structures/Evolution/EvolutionType.cs#L8

**Comment by Ecroton** [comment]
Thanks so much for replying! Still a bit confused, but I get that it's built into it, and must be hard to change or edit. I'm really loving this software! My experience is extremely limiting, but even just with what I've been able to do I think I could make a full-on awesome mod! Excited to dig into it! I did have one other question, if you don't mind. Is it possible to edit Pokedex entries? Would love to add entries for all the ones that are missing them. Just simply copying and pasting text, height, weight, etc. Seems like it would be an easy thing to do, but just can't figure it out at the moment.

**Comment by JelleInfinity** [comment]
Actually it's a lot harder then you imagine.
Also, for swsh the tools to be able to achieve this are lacking, and you would need to write code to make it work.

To give you an idea of what would be necessary:
It's not just the Pokedex entry, along with that you need the graphics. (The icons in the box, the models for battles etc.)
You need to add entries in all files for AI, movesets, held items/item drops, where they spawn, and the list goes on.

I've been working on getting all of this in for PLA and it has already taken me over 3 months (given that I have a day time job). And I'm a professional programmer.

Not to discourage you, but be aware of what you're getting into :p

**Comment by Ecroton** [comment]
Thanks for replying! I'm a bit confused, however. So from what I can see in the Pokedex it looks like you would indeed need the character model with motion (simple relaxed motion animation), the character icon, habitats with weather, name, height, weight, description, male or female option with possible variants, and number battled. However all of this information is either already in the game, as well as pknx, or gathered by code, ie when I change a habitats Pokemon in pknx it is reflected in the Pokedex, so it must be grabbing it with code, as well as the number battled. The only information they don't have is the description, height, and weight, which I could easily get online and input. The game already has their movesets, icons, etc, as I'm able to easily drop them into any habitat fully fleshed out with pknx (minus a dex entry), the only thing I'm not sure about is the simple motion animation, but I suspect that is in their as well (I'd even be okay with just the model without animation). I don't know, maybe there's something I'm missing. I'm definitely not a professional programmer by any means, but I have a bit of experience with it, and one of the things I've learned is that things are always more complicated then you think they will be. Lol.  I just think with all the amazing things this app can do it shouldn't be too difficult to add a Pokedex modifier. Definitely beyond my scope though, so I'll keep my fingers crossed for a future update and just keep having fun with it for now. Good luck with your PLA project! If you can let me know when you finish it I would love to check it out! Just finished my dex on there a few weeks ago for the first time! Never done that before, as you always have to trade, go online, blah-blah-blah. One of the things my mod will definitely correct for Sword/Shield.

**Comment by JelleInfinity** [comment]
> However all of this information is either already in the game
This is only true for pokemon that are currently in the game. The game files contain a database file called the 'Personal Table'. It has data on all pokemons, but this information is missing for mons not in SV.

Not long ago I fixed this for PLA to pull the missing data from SWSH. See the function on [this line](https://github.com/kwsch/pkNX/blob/98546946b764a7c4b524a0933d689796485870a6/pkNX.Structures.FlatBuffers/Arceus/Integration/PersonalTable8LA.cs#L112).

To give you an idea, this is page for a simple pokemon entry in PLA. And this is only it's personal info
![image](https://user-images.githubusercontent.com/60387522/208317499-3dcdc7e2-0934-40cc-9455-7756845401cc.png)

>The game already has their movesets, icons, etc
True, the game has the info for these. However moves are linked to each pokemon individually. This is what we call the movesets/learnsets. Icons are only there for mons that exist in SV.

Which is this tab:
![image](https://user-images.githubusercontent.com/60387522/208317533-cdc870fc-20b5-4826-a355-be8a9c27d961.png)

> the only thing I'm not sure about is the simple motion animation, but I suspect that is in their as well (I'd even be okay with just the model without animation).

Again, this only exists for mons that are currently in SV. If you want the rest, you will need to grab this info from PLA or SWSH and to a whole bunch of converting. A whole lot of people are working on this a lot letely, trying to figure out these models and animations and how to port them from one game ot the other.

**Comment by Ecroton** [comment]
Oh man, I just realized, I must've screwed up in my initial question. I'm only interested in adding Pokedex entries for the Pokemon that have already been added to the game, but just don't have dex entries (ie, Crown Tundra legendaries, or pkHome entries). Believe there's around 70 of them at least, and I found out last night that (at least pknx) DOES have the height and weight as well! Only thing I'm not seeing is the actual Pokemon description, which I would love to add. They just don't have a dex number assigned (1-400 for the main dex). I'm gonna try out just making one of them 401 and seeing what it does. Good chance it'll crash, but fingers-crossed I get lucky. Still doesn't help me with adding any descriptions, but maybe those are in there too, and I just can't see them. I also figure there may be a boolean somewhere like "HasDexEntry=True/False", which would fail to trigger for these guys, but still gonna try. I just don't understand how they could add all the awesome legendaries to the game, then leave out their dex entries. Always loved seeing that come up after the first catch. Also noticed they don't track which ones have been caught (Pokeball icon near the name). Guess it makes sense, since you're only supposed to be able to catch/encounter one of each. Lol

**Comment by Ecroton** [comment]
So apparently I can't edit the Pokedex number. Kind of a bummer. Interestingly though, when I clicked the "Master Dump" option it created a dump folder with a Pokedex entry that has all the ones I'm interested in adding, labeled "Foreign", along with the GalarDex, ArmorDex, and CrownDex.

**Comment by JelleInfinity** [comment]
Technically you can edit the dex number, but the textbox is just disabled in that editor. You could totally make changes to that tho.

By default it is disabled, because of the side effects it could have on the game
