### ISSUE TITLE
Legends Arceus randomization issue

### ISSUE THREAD

**Issue by RevanXVIV** [kwsch/pkNX#308]
Ok I don't know if this is a new issue or what, but it seems that when randomizing starters in legends arceus the professor doesn't acknowledge you caught his 3 pokemon if they are randomized, is there a way to fix this or this some kind of work around? I'd actually like to have a random starter, but it doesn't seem possible at the moment.

**Comment by kwsch** [comment]
Starters are shiny locked, thus forbidden from being randomized. Not sure what you did.
https://github.com/kwsch/pkNX/blob/98546946b764a7c4b524a0933d689796485870a6/pkNX.WinForms/Subforms/AreaEditor8a.cs#L110

**Comment by RevanXVIV** [comment]
You know you can disable the shiny lock right? Also why does shiny lock make them forbidden from being randomized? That makes no sense considering the SWSH starters are also shiny locked, which can also be removed.

**Comment by RevanXVIV** [comment]
Btw I'd like to add the starters were randomized via gift pokemon.

**Comment by kwsch** [comment]
If you remove the shiny locks then randomize, of course things will break. The program was made with the assumption that all shiny locked encounters shouldn't be randomized, so they're skipped. By removing that attribute from the encounter, the randomization logic no longer skips the encounters in question.
