### ISSUE TITLE
Are gift pokemon not a supported randomization feature in legends arceus?

### ISSUE THREAD

**Issue by RevanXVIV** [kwsch/pkNX#309]
Ok so I've only had the game for a few days and am still learning the proverbial ropes of what mods can and cannot work, I made a thread earlier mentioning an issue I had with the randomized starters, to which I was told was impossible to work.

So my question is: Are randomized gift pokemon not a supported feature for PLA? Just asking so I know if I need to make another seed or not.

**Comment by kwsch** [comment]
If you don't see an editor for it, then it doesn't have an editor.

PLA only has one gift (Alolan Vulpix), so not like it's anything interesting to randomize.

**Comment by RevanXVIV** [comment]
Umm, that's not actually true. The gift tab includes all the starters in PKNX. As well as the following: Vulpix, Two palkia's, a dialga, and Arceus. So the starters in that tab aren't meant to be there then, good to know.
