### ISSUE TITLE
PLA Wild Starters at Start keep randomizing and I can't figure out how to work around this.

### ISSUE THREAD

**Issue by RevanXVIV** [kwsch/pkNX#310]
Ok so I'm curious what map are the 3 wild starters on? Is that the 3 encounters in Jubelife? Cause I'm pretty sure it is, which if that's the case I'll just leave it unrandomized, I'm just looking for confirmation so I know exactly what map to avoid randomizing.

**Comment by kwsch** [comment]
Please stop opening new issues. There is no issue with the program.

If you want to randomize the game, start from a clean dump, then do whatever cosmetic alterations after.

**Comment by RevanXVIV** [comment]
I was just trying to figure out why the wild starters at the beginning of the game were preventing me from completing the catching tutorial, I figured it out. Also you were wrong, randomized starters 100% work. I figured out how to get the randomized starters working after experimenting with a couple of settings.
