### ISSUE TITLE
Question: Do PLA Shiny odds modifiers work in PKNX?

### ISSUE THREAD

**Issue by RevanXVIV** [kwsch/pkNX#312]
Ok so I set the shiny odds as follows for my randomizer:

10 Dex: Original odds 1, modified odds 10

Perfect Dex: Original odds 2, modified odds 20

Shiny charm: Original odds 3, modified odds 30

Will this actually work? I've hit the 10 cap for ralts like 2 hours ago and haven't seen a single shiny.

EDIT: Do I also have to change the debug max setting as well to match the new shiny odds I put in?

**Comment by JelleInfinity** [comment]
Those work, but are still quite low odds that is 1+10+20+30 = 41/4096 odds

**Comment by RevanXVIV** [comment]
Yeah I thought about that, tried changing the odds to 85, 170, and 255, that worked pretty well I just misunderstood how the shiny odds modifications worked.
