### ISSUE TITLE
SwSh Starters not randomizing now, what is going on?!

### ISSUE THREAD

**Issue by RevanXVIV** [kwsch/pkNX#315]
Ok I KNOW this is a bug because the last build I was using actually randomized my starters, so I'd like to know why the current build won't randomize starters in Sword and Shield.

**Comment by duckdoom4** [comment]
Depends on what your 'old build' is. The code hasn't changed in 17 days. So unless you never updated when you first used it, nothing has changed

**Comment by RevanXVIV** [comment]
The build I used ran on net 461

**Comment by duckdoom4** [comment]
Closing in favor of #198
