### ISSUE TITLE
Unable to randomize trainer and wild encounter (PKMN Shield)

### ISSUE THREAD

**Issue by Hitmontop91** [kwsch/pkNX#320]
All other fields can be randomize except for trainers and wild encounters
![Type Initializer pkHex](https://user-images.githubusercontent.com/110528293/214100054-e968c4c3-02b6-4c31-bfe6-6216311f6ad3.PNG)

**Comment by duckdoom4** [comment]
The randomizer is non functional for PLA, this error is unrelated to the randomizer and seems like it should be solved tho

**Comment by Hitmontop91** [comment]
I forgot to mention that this is Pkmn Shield, not PLA.

**Comment by dschu012** [comment]
I have the same issue w/ Shield

**Comment by fa7alis** [comment]
I'm getting the same error while trying on both Sword and Shield. This error pops up whenever I try the Pokemon, Trainers, or Wild option. Everything else appears to be working correctly.

**Comment by Hitmontop91** [comment]
Hi, I tried the 2020 release and able to randomize sword and shield. I hope this can be fixed in the next update.

**Comment by Dubuyu** [comment]
Same here. Tried earlier versions of the pknx and none have worked. Hope this is resolved soon.

**Comment by duckdoom4** [comment]
We don't need more 'me too' comments. It will be solved when someone finds the time to look into it
