### ISSUE TITLE
could not load fiel or assembly error 

### ISSUE THREAD

**Issue by Skertelles** [kwsch/pkNX#323]
<img width="476" alt="Capture" src="https://user-images.githubusercontent.com/126305106/221333033-b5b2c2ad-8ce4-49eb-bb46-cbebe9b8760f.PNG">

so, I been trying to use the pknx randomizer for a while and keep getting errors, but when I thought I got it finally work I got this error. I don't know what to do.

**Comment by kwsch** [comment]
Try using the latest commit, and ensure you're unpacking the program zip correctly.
