### ISSUE TITLE
SV Dump 'Text Files' error / folders are empty

### ISSUE THREAD

**Issue by SuperPxL8** [kwsch/pkNX#324]
Hello and thanks for creating pkNX, currently I am content with the read only/export functionality for Scarlet and Violet, however when trying to export the Text Files I am running into this odd error and I was hoping it could be clarified what is going on. 
I'm using a Violet romfs with update 1.20 and Violet romfs with update 1.10 in order to compare differences, but the error also occurred with Scarlet 1.00 and Violet 1.00

When trying to dump the Text Files it reports me that the folders  '..\Dump\archive\extracted\arc' does not exist. _See screenshot_
![err001](https://user-images.githubusercontent.com/91283063/222782042-72e58e83-2e15-4a19-ad02-afa75eeb0bce.PNG)
I have tried placing the romfs in the root of my C: drive to see if I was making a rookie mistake, but it kept occurring.

When I close pkNX and I create the missing folder 'extracted\arc' manually and try again, then it creates the files and folders in ..\Dump\text\ but all the language folders contain empty text files. 
![err002](https://user-images.githubusercontent.com/91283063/222782045-995e3584-2a81-4737-9f93-cba9ca3cd440.PNG)

All other options Personal Stats, Raids, Trainers, Encounters, Moves and Cooking works fine in either romfs 1.10 or 1.20. 
So I thought it might be a permissions error and attempted to run pkNX as administrator, but the windows default *ding* sound can be heard whenever I press the button. The same sound when the other options have run successfully.

I was hoping for help in resolving this issue?

**Comment by kwsch** [comment]
Dump the archives first.

**Comment by SuperPxL8** [comment]
I'm embarrassed with how stupidly easy this was to resolved. My apologies for wasting your time I appreciate your quick response.
