### ISSUE TITLE
AI Flags

### ISSUE THREAD

**Issue by AedraRising** [kwsch/pkNX#325]
I'm in the middle of editing the trainers for a mod I'm making but when looking at all of the AI bits there's no explanation given for what changes when you alter "Allowance," "PokeChange," and the "Raid" AI bits. It turns out that the dump itself contains the battle scripts but they all have the .amx file extension and I have no idea how to open them to examine them. Any help?

**Comment by kwsch** [comment]
https://github.com/kwsch/pkNX/issues/21

**Comment by kwsch** [comment]
Undocumented what the actual defined behavior of each is.
