### ISSUE TITLE
PLA Wild Randomizer Broken

### ISSUE THREAD

**Issue by BigKat2001** [kwsch/pkNX#329]
Hello, I am writing as I believe the PLA wild spawn randomizer no longer functions as it once used to. It appears that in the Area Editor tab, when PkNX loads the areas' information, the "Table" section of the data is no longer filled in like it used to be with some Array value/pointer. I know it used to work on a previous build (the build I had working had a folder called net6.0 instead of the latest net7.0 so maybe it happened between the .net changes?), however now when I randomize areas, no spawns are loading at all, except for Mass Outbreaks and Shaking Trees/Ore Deposits (which are still randomized properly). 

I have read over a few of the more recent reports about PLA and I understand that there isn't much work being put into that side of things, and I know it never really fully "worked" in the first place, but I am hoping that maybe this might be something that isn't too much of a hassle to look into. If not I totally understand, I can live without a PLA randomizer after all. 

I attached a picture of the screen in question, hope that helps as my description might not have been the best. And obviously, if I am just doing something stupid and this is an issue on my end, I apologize for the inconvenience. Thanks for all the work you all have put into this program!
![Capture](https://github.com/kwsch/pkNX/assets/133474438/3d5e234d-a0a9-4292-a801-9c472292ca3a)

**Comment by duckdoom4** [comment]
See #318

**Comment by BigKat2001** [comment]
Alrighty, thanks for the reply! Is there any place I can find older builds of the program by chance? I tried looking on the repository but it appears stuff older than 30 days gets automatically purged. If not, no biggie

**Comment by duckdoom4** [comment]
@kwsch Are they available?
