### ISSUE TITLE
No more option for a Pokemon's ability in trainer editor

### ISSUE THREAD

**Issue by Kobazco** [kwsch/pkNX#33]
Hey just wanted to notify you guys that after the changes today to the trainer editor to allow editing of the Dynamax levels and other features, the box to decide a Pokemon's ability is no loner there. Also, there's a "Can mega" checkbox now. Not sure if this was intentional or not.

Anyways, there is currently no way to change trainer Pokemon abilities with the latest commits.

**Comment by pratmangalore** [comment]
I'd like to add that there is no option to give held items to trainer pokemon in the trainer editor too.
