### ISSUE TITLE
Shiny Rate question (Shield)

### ISSUE THREAD

**Issue by KirbyKing186** [kwsch/pkNX#330]
Shiny Pokémon obviously are rare, freaks of luck that by pure happenstance show up during a playthrough. I have not received my first badge and I already have two (snom and tyrunt). I feel like the odds have been raised, although I have not changed any settings in the “shiny rate” option in PKNX. Am I just lucky or does randomization boost odds somehow? I re-randomized the romfs after I found snom, just in case there was any errors with the shiny rate. Both configuration files had no results when I CTRL-F’d “shiny”

Tangent: a trainer in a Max Raid Den had a shiny Fomantis. This is when I realized that I accidentally set trainer shinies to 2.5%, which in the next randomization I turned down to 0%. This shouldn’t effect wild encounters though correct?

**Comment by kwsch** [comment]
Randomization does not change the shiny rate, which is an exefs patch cheat.

Trainer shinies are unrelated to wild.

**Comment by KirbyKing186** [comment]
So I got 2 full odds shinies? I played through the entirety of PKMN Emerald randomized and not a single shiny, but two full-odds are awesome now

**Comment by duckdoom4** [comment]
Emerald odds are 1/8192, compared to the lower default of 1/4096 in sword/shield
