### ISSUE TITLE
Issues using pknx with PLA due to file being used error

### ISSUE THREAD

**Issue by Shinygati** [kwsch/pkNX#332]
So this was working fine earlier but after a while i keep getting this error when trying to save my changes, tells me it cannot access the file poke_ai.bin because it's being used by another process, there is only one instance of pknx opened and i've tried restarting several times, also running on windows 11 and using the latest pknx build.

![image](https://github.com/kwsch/pkNX/assets/17960201/607c8216-464b-4948-a54e-96715b3aec20)

**Comment by duckdoom4** [comment]
Sounds like a windows issue. Try cutting the file and pasting it in a different location, see if windows gives you the same message

**Comment by Shinygati** [comment]
So i can't cut or copy the file while pknx is opened but after closing it I can copy, cut or delete the file just fine
