### ISSUE TITLE
Ability to load romfs back into the dispay

### ISSUE THREAD

**Issue by Dubuyu** [kwsch/pkNX#333]
The display that allows you to view pokemon abilities and learnsets is extremely handy while playing, and after closing pknx I found I could not load it back up with the romf that I was previously using, with it defaulting to the bass game. Furthermore, I am now unable to change alter certain parts of the romf without re-randomizing the whoel thing due to the inability to load the current romf into pknx. Is there way to do this? If not, it would be an extremely useful feature.

**Comment by kwsch** [comment]
Opening the editors does not trigger randomization. If you have removed the layeredfs folder, then there's no other data to use besides the original base ROM.

Copy instead of moving.
