### ISSUE TITLE
PLA Starters Not Spawning

### ISSUE THREAD

**Issue by rwtro** [kwsch/pkNX#335]
Hi, I'm not sure if there's a setting/option I missed, but it looks like the starters you capture at the start of the game don't spawn when using the randomizer?

**Comment by kwsch** [comment]
https://github.com/kwsch/pkNX/issues/308#issuecomment-1366287654

> If you remove the shiny locks then randomize, of course things will break. The program was made with the assumption that all shiny locked encounters shouldn't be randomized, so they're skipped. By removing that attribute from the encounter, the randomization logic no longer skips the encounters in question.

**Comment by rwtro** [comment]
See that's the thing, I decided to do a fresh dump and randomize without removing the shiny locks and still had the same issue. So, I disabled the randomizer until selecting my starter. However, the game just crashes when I pick my starter. Is there a recommended older build I can use of the randomizer for Legends Arceus?

**Comment by kwsch** [comment]
> "disabled the randomizer" -> "game just crashes"

I'm not sure what your issue is then. Be sure you don't have any other cheat code apps active.
