### ISSUE TITLE
Level 100 random pokemon

### ISSUE THREAD

**Issue by poudmajik** [kwsch/pkNX#338]
I was playing a randomized run of pokemon sword when out of nowhere a random trainer sent out a level 100 nidorino that only knew struggle (at that point in the game the pokemon were about level 30) and i'm pretty sure that's not supposed to happen.

**Comment by poudmajik** [comment]
I got into another trainer battle and the second pokemon was also the same pokemon so now i'm really sure that my randomizer is broken

**Comment by kwsch** [comment]
If you randomized multiple times with the level boost setting active, you'll end up with level 100 stuff. Delete the layeredfs folder and re-randomize.
