### ISSUE TITLE
Cannot open S/V rom because of Failed to Initialize ROM data.

### ISSUE THREAD

**Issue by Leo-Sag** [kwsch/pkNX#340]
Hello team,
I have an issue about open S/V rom(Japanese) via PkNX.
I dumped rom with update along with tutorial.(https://projectpokemon.org/home/forums/topic/57498-dumping-games-for-pknx-rom-editingrandomization/)

However, PkNX says my dump has "Unknown GameFile provieded. (Parameter 'GameText2') and I cannot open the rom.
Please see the attachment and please help how to resolve this error.
Thanks and regards,
![pknxerror_20230912](https://github.com/kwsch/pkNX/assets/15900684/025ead1d-4a65-4e3b-9a2c-caad53e11704)

**Comment by duckdoom4** [comment]
Ah, seems like something I did for PLA is affecting SV. I'll look at it tomorrow. In the meantime you can grab a slightly older version

**Comment by Leo-Sag** [comment]
Thank you very much for your support.
I tried 3 version on Pipeline, however I faced the same message as above or failed to open.
Latest one(20230910.5) and slight old version(20230831.1) are the same Error message.

20230823.1 has another error below.
![image](https://github.com/kwsch/pkNX/assets/15900684/29bfddba-71a9-4cee-9a26-bd6019bf9c45)

I want to be able to deploy this Rom with the latest version, so you can ignore the message below.
Thanks again!

**Comment by duckdoom4** [comment]
The offending commit is this : https://github.com/kwsch/pkNX/commit/1e7cb1d6b1e5211865860c73d38552a3a626bde4

So you need the version before that

**Comment by duckdoom4** [comment]
Fixed it for you in the latest release

**Comment by Leo-Sag** [comment]
Thank you for your quick and kindly support!
I checked and open the rom.
![pknx_fixed](https://github.com/kwsch/pkNX/assets/15900684/798942e8-c66b-4563-8add-40684ab02dde)
