### ISSUE TITLE
Error message for dumping SV roms with Deserializer type'Lazy'

### ISSUE THREAD

**Issue by Leo-Sag** [kwsch/pkNX#341]
Hell team,
I tried to dump master, field or dialog game from the SV roms with the latest pipeline release(20230912.4), however it shows the same error for some options.

Such as 
///Field > Map Viewer
![image](https://github.com/kwsch/pkNX/assets/15900684/e5328951-d4f7-4a04-950b-deeb625363af)

///Master dump > Move
![image](https://github.com/kwsch/pkNX/assets/15900684/d288e304-3823-4a81-bfbf-feadb09b2e09)

Or the other error for Dialog feature,
///Dialog > Common
![image](https://github.com/kwsch/pkNX/assets/15900684/b8e32d79-447d-47a9-899a-8d1296948f62)

And also it worked and created some files, which do not have any bytes,
![image](https://github.com/kwsch/pkNX/assets/15900684/43e1b08e-ad74-4504-bf28-71754457f0c5)

Would you mind to share how to resolve dumping SV roms?
Thank you for your support.

**Comment by meatlover123** [comment]
Did you find a fix? I'm having the same problem.

**Comment by duckdoom4** [comment]
There won't be a fix until someone changes the word 'Lazy' to 'GreedyMutable' or 'Progressive' where it's used in code. (and verify that it works after).
