### ISSUE TITLE
Questions about text export

### ISSUE THREAD

**Issue by Digote** [kwsch/pkNX#342]
**First of all, congratulations on the project. There is no other project that does the same thing.** We use it extensively to translate Pokémon S/V, even though it doesn't have full support yet. We managed to dump it by replacing the files from Pokémon Legends Arceus, and it works.

Regarding the latest updates in the text export feature, the new model with Hash and file separation looks great. **My question is whether you will be adding a batch export feature because currently, it exports each text file separately. It would be great to have both options.**

I apologize if this option already exists, and I just haven't found it.

Once again, congratulations on the project.

![Text Editor](https://github.com/kwsch/pkNX/assets/45742711/90308ddf-619c-4fd2-88cf-26c0c7262fcb)

**Comment by duckdoom4** [comment]
Right, I removed that feature cus I thought we had another export method to do batch export. That one's broken now. I can quickly hack in a batch export option and then fix it properly later

**Comment by duckdoom4** [comment]
There, using the latest version you can hold shift while pressing the export button to get a batch export folder selection popup.

Let me know if you also need batch import

**Comment by Digote** [comment]
I just tested, and the export part works perfectly. I had even created a tool outside to separate the files in the old way it used to export, but now it's resolved.

**I would need the import part as well, thank you very much for the support.**

I'll test it thoroughly tomorrow when the DLC comes out.

![NEW_2](https://github.com/kwsch/pkNX/assets/45742711/655125eb-b52f-4813-88b1-35dee35cbeb3)
