### ISSUE TITLE
wild editor doesn't seem to remember changed tables

### ISSUE THREAD

**Issue by gr3ger** [kwsch/pkNX#35]
Game: Pokémon Sword
App version: https://github.com/kwsch/pkNX/commit/59f764518f289b67ebe1b8e85b1602c3c9029822

I'm currently trying to sync sword/shield tables to remove all exclusives.
However, if I add a pokemon to "Intense Sun" etc in an area, switch to another area and then back, the change is gone.

The odd thing is that it's not consistent, I'll try to make a video of it later if it happens again.
Am I doing something wrong or how am I supposed to make multiple edits before saving?

EDIT:
Video of it happening here
https://imgur.com/sRvtgTL

**Comment by dderek** [comment]
Has anyone found any solution to the above problem?

**Comment by Jack-Rickwood** [comment]
![image](https://user-images.githubusercontent.com/40942787/69629943-aa86e380-10a0-11ea-9888-828e0d790896.png)

**Comment by Jack-Rickwood** [comment]
I think we have to wait

**Comment by kwsch** [comment]
Fixed via https://github.com/kwsch/pkNX/commit/7237f7264f621dac62ccde298f0cfa09b04ee7ac
