### ISSUE TITLE
Leveling Up Pokémon With Edited Stats Causes Them To Bug Out (Sword/Shield)

### ISSUE THREAD

**Issue by RuinousPrincess** [kwsch/pkNX#350]
I decided to edit the stats of Pokémon I use, but for some reason if you level them up to level 100 their stats have a +- sign then end up at 6 (any low number tbh). Like Falinks, I got 255 in HP, Sp.ATK and SPD, but going to lvl to 90-100 reverts the Sp.ATK to 6. This seriously happens with every Pokémon I use, so it seems like the game or PKNX can't handle to type of stats due to probably calculation issues with them being over 600 at that level. I even tried a Hatenna, her Special Attack went right to 0, didn't even change to a 6. All I done was use rare candies and tested it, it bugs out on any Pokémon with maxed/hacked IVs/EVs

And I found out what is actually causing it. It's due to EVs of a Pokémon being 252, and then leveling them up past 90-100 causes their stats to completely glitch out. Removing the EVs by using PKhax on whatever stat was edited in PKNX to 255 will work, but for some reason Speed isn't affected at all, leaving ATK and Special Attack being the only ones I notice to be revert to low numbers if maxed EVs are used. I'm not sure if any number below 252 will glitch it out since I haven't gotten that far in Sword to notice, but it's very clearly related to EVs period causing this odd behavior. I really hope it can be fixed, if possible.

![Desktop Screenshot 2023 10 11 - 00 16 00 20](https://github.com/kwsch/pkNX/assets/83746056/8b14eb59-3b3f-4c51-a09b-97f9390a6f48)
![Desktop Screenshot 2023 10 11 - 00 16 09 01](https://github.com/kwsch/pkNX/assets/83746056/6c92b1ed-0bdc-4d01-9bd2-66934c8d5488)

**Comment by duckdoom4** [comment]
That's because the stats are a byte value. It has a possible range from 0 to 255. Anything higher than 255 and it will loop back to 0.

Nothing we can do about this, that's hard coded in the game. Just don't put them so high
