### ISSUE TITLE
Feature request: better readme.

### ISSUE THREAD

**Issue by svnv-svsv-jm** [kwsch/pkNX#353]
There are no usage instructions in the README.md. I think is a bad choice. People coming here should find the usage instructions in the same place :)

For example:

I'd like to use this tool to dump SV, but how?

**Comment by svnv-svsv-jm** [comment]
Hello, thanks for replying.

I get it, but (maybe wrongly) I was told that this tool can also be used to dump a copy of SV. If this is the case, then why can't I find instructions to do so anywhere? Or is this information wrong?

Thanks for your time!

**Comment by kwsch** [comment]
Once you've ripped the xci/nca from the console/cart, you can use tools like hactool/nxdumptool to unpack into romfs/exefs files.

https://github.com/DarkMatterCore/nxdumptool
https://github.com/SciresM/hactool
https://github.com/Atmosphere-NX/hac2l

There should be guides on the internet.

pkNX "dumps" by further processing the game files into something human readable/reusable. The initial setup can be done by other tools, so it's less things for pkNX to maintain/update if it only needs to handle the unpacked romfs. I don't want to have to maintain guides when other tools update 🥲

**Comment by svnv-svsv-jm** [comment]
Yes, I totally understand it.

Last thing, then: you say 

> pkNX "dumps" by further processing the game files into something human readable/reusable

But where/how? Perhaps this is what I've heard around, but never seen a doc for this. I used pkNX mostly to edit PLA.
