### ISSUE TITLE
Pokemon Legends Arceus: Catching Tutorial pokemon not spawning

### ISSUE THREAD

**Issue by Pixel215YT** [kwsch/pkNX#356]
I've randomized Pokemon Legends Arceus, and when talking to Leventon in the very beggining after getting the Arc Phone, in the catching tutorial there is nothing to catch, like I get the 50 pokeballs, but the 3 starters don't show up for me to catch therefore I cannot proceed with the game.

**Comment by kwsch** [comment]
Duplicate
https://github.com/kwsch/pkNX/issues/335
