### ISSUE TITLE
Issue with shiny rate 

### ISSUE THREAD

**Issue by HarukaNanami** [kwsch/pkNX#359]
![Screenshot_1](https://github.com/kwsch/pkNX/assets/159954566/1077c6dd-5285-4971-90b3-f32d42bcbb19)

hi, i use pokemon sword 1.3.2, and the program give me this error

**Comment by pantsman0** [comment]
You haven't dumped the ExeFS, only the RomFS. The shiny rate editor works by patching the game executable, so you need to dump the ExeFS.
