### ISSUE TITLE
Failed to initalize ROM data

### ISSUE THREAD

**Issue by dookiecheese** [kwsch/pkNX#363]
Use ryujinx and followed all steps but this pops up help
![image](https://github.com/kwsch/pkNX/assets/158014551/1c738467-478a-40b1-88a7-92bd79145c09)

**Comment by kwsch** [comment]
> with updated patches merged in (if applicable)

^ relevant part of the popup message that you didn't do. pkNX does not support unpatched versions of the game; dump the game patch content from the Nintendo CDN / console and then merge it into the romfs/exefs folders to get an "updated" romfs/exefs.
