### ISSUE TITLE
Exception Error For PKHex.Drawing.PokeSprite.Spriteutil

### ISSUE THREAD

**Issue by ToonKnight** [kwsch/pkNX#367]
After building the software and following the guild on how to build and format the file location all the randomizing of items and other work fine but as soon you try to do something related to Pokemon an error pops up a lot of people seem to be having this issue.

Tried with Sword

Pokemon 
![image](https://github.com/kwsch/pkNX/assets/76595733/2aaf3683-05a5-4548-8635-4ad59c9f6a0a)

Wild
![image](https://github.com/kwsch/pkNX/assets/76595733/85315fc6-734e-4193-a027-44fe70745057)

Trainers
![image](https://github.com/kwsch/pkNX/assets/76595733/a6c0658a-9587-468a-993a-fff54afa9c6b)

**Comment by kwsch** [comment]
https://github.com/kwsch/pkNX/commit/4deec6fc7ab1bcfa5a89cdff36593bbdb6f3898c

NuGet for PKHeX.Core was updated, I forgot to manually copy in the pokesprite dll's as the core API surface was changed. Just need to rebuild PKHeX and copy updated dll's over since those aren't on NuGet...

**Comment by Domemilano07** [comment]
did it get fixed?
