### ISSUE TITLE
cant edit wild, Pokémon or trainers 

### ISSUE THREAD

**Issue by danyome** [kwsch/pkNX#368]
wild pokemon
![Screenshot (55)](https://github.com/kwsch/pkNX/assets/119982771/5f2a197a-ecd8-4aeb-8f46-8755d6f40baa)
trainers
![Screenshot (56)](https://github.com/kwsch/pkNX/assets/119982771/bfea30f5-bd3e-4f88-88e7-22b3847e4ea0)
pokemon
![Screenshot (57)](https://github.com/kwsch/pkNX/assets/119982771/55ba34f7-7b9a-4249-8fc2-c6c251f05995)

How to fix

**Comment by kwsch** [comment]
Duplicate
https://github.com/kwsch/pkNX/issues/367
