### ISSUE TITLE
How to open? Pokemon Sword

### ISSUE THREAD

**Issue by RentaroArts** [kwsch/pkNX#37]
So I'm following a tutorial for Pokemon Lets Go, and I'm at the point where I open the folder that's named "9226d941a6b4d9df42ff2fa4213d1679.nca" with pkNX but I get an error saying that it is an invalid folder. How to I open the folder?

**Comment by gr3ger** [comment]
you need to open the folder with exefs and romfs inside it, not just an NCA file.

**Comment by RentaroArts** [comment]
I am opening the folder

**Comment by kwsch** [comment]
Be sure you are using the latest commits rather than a download that was prior to SW/SH release date.

**Comment by RentaroArts** [comment]
It's still giving me the error "Invalid folder loaded. Unable to recognize game data. C:\Users\King\Desktop\hactool\extracted\9226d941a6b4d9df42ff2fa4213d1679.nca"
And that's the folder that holds all my exefs and romfs
