### ISSUE TITLE
Randomized wild pokemon options are only weak pokemon

### ISSUE THREAD

**Issue by Master-Luigi-12** [kwsch/pkNX#371]
my pokemon are only randomizing to weak ones with the strongest mon being a terrakion on axew's eye. The randomization options are seemingly non existent in newer versions while on the version I used to use before I lost all of my computer data would have legendaries and fully evolved pokemon spawning everywhere
![20240530_055742](https://github.com/kwsch/pkNX/assets/171254959/fa760eff-6f33-49d5-8893-d5d1362f6bd2)

**Comment by kwsch** [comment]
Default settings randomize by BST, not purely random. 
Try un-expanding the editor window to see if the options become visible.

**Comment by Master-Luigi-12** [comment]
That didn't change anything it's still the same 3 options

**Comment by kwsch** [comment]
Unable to replicate:
![image](https://github.com/kwsch/pkNX/assets/6393368/51718d3b-29e2-4af7-9f2b-c48659bfe8b3)

**Comment by Master-Luigi-12** [comment]
I don't know if it matters but i used nxdumptool rewrite to dump the game

**Comment by kwsch** [comment]
Try deleting the rand settings (json) files next to the pkNX exe. It should be creating the property grid editor for you to change randomization settings.

Otherwise, you can change the randomization settings yourself in a text editor like notepad while pkNX is not running.

**Comment by Master-Luigi-12** [comment]
Changing the settings through a text editor worked thank you

**Comment by Master-Luigi-12** [comment]
Changing the settings through a text editor worked thank you
