### ISSUE TITLE
One Down another problem to go 

### ISSUE THREAD

**Issue by Moddedmyth** [kwsch/pkNX#374]
![image](https://github.com/kwsch/pkNX/assets/171505065/76c11da7-3312-4b12-a12f-7ecb109ccdd6)

**Comment by kwsch** [comment]
Please do not create new issues for each incremental progression of your problem.

The error message is clear enough. You need to dump ALL of the romfs and exefs files, including patches merged in, as previously mentioned. The file counts expected are documented in the source code:

https://github.com/kwsch/pkNX/blob/5b5a196bdbea0b4855760b516b186fb8df363117/pkNX.Game/GameLocation.cs#L76-L97

**Comment by Moddedmyth** [comment]
Sweet thanks!
