### ISSUE TITLE
At a loss

### ISSUE THREAD

**Issue by Mrgamer2240** [kwsch/pkNX#375]
Where do I put the "Gamelocations.cs" file is it RomFS ExeFS  or somewhere else entirely?

**Comment by Moddedmyth** [comment]
Patch content as in DLC correct?

**Comment by kwsch** [comment]
Correct, DLC is a patch to the base game ROM.

**Comment by Mrgamer2240** [comment]
I was successful at opening pkNX without issues but the mods I enabled from pkNX don't appear during launch, I'm using atmosphere currently is it compatible?

**Comment by kwsch** [comment]
You need to load the files back to your console in the correct folder structure so that layeredfs works as intended. Double check you've put the edited file folder in the right location and are using CFW. Not a pkNX issue.

**Comment by Mrgamer2240** [comment]
If I'm correct the structure should be atmosphere/contents/01008DB008C2C000, correct?

**Comment by kwsch** [comment]
yes
`atmosphere/contents/01008DB008C2C000/romfs` etc.

**Comment by Mrgamer2240** [comment]
Okay my path is Atmosphere/Contents/01008DB008C2C000/RomFS and Romfs meta data/bin/archive pml and trainer etc.  But the modifications don't work. I tried modifying the wild but still no luck, nor trainers either.

**Comment by Mrgamer2240** [comment]
Okay my path is Atmosphere/Contents/01008DB008C2C000/RomFS and Romfs meta data/bin/archive pml and trainer etc. But the modifications don't work. I tried modifying the wild but still no luck, nor trainers either.

**Comment by Mrgamer2240** [comment]
Okay my path is Atmosphere/Contents/01008DB008C2C000/RomFS and Romfs meta data/bin/archive pml and trainer etc. But the modifications don't work. I tried modifying the wild but still no luck, nor trainers either.
