### ISSUE TITLE
pkNX Error on certain tabs

### ISSUE THREAD

**Issue by ItsJustLori** [kwsch/pkNX#379]
Hey, I tried to make a Pokemon sword randomizer with pkNX, but when I go to certain tabs, like Pokemon or items, I get error messages that I don't understand.

Error message that comes up when I click on Pokemon:
Index was outside the bounds of the array.
at pkNX.Structures. Personal TableExt.GetFormList(IPersonalTable pt,
String]] species) in
D:\a\1\s\pkNX.Structures\Personal\Interfaces\|PersonalTable.cs:line 87
at pkNX.WinForms.PokeDataUI..ctor(PokeEditor editor,
GameManager rom, GameData data) in
D:\a\1\s\pkNX.WinForms\Subforms\PokeData Ul.cs:line 48
at pkNX.WinForms.Controls.EditorSWSH.EditPokémon() in
D:\a\1\s\pkNX.WinForms\Main Editor\EditorSWSH.cs:line 86
at System.RuntimeMethodHandle.InvokeMethod(Object target,
Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object
obj, BindingFlags invokeAttr)

Error message that comes up when I click on Items:
Index was outside the bounds of the array.
at
System.Linq.Enumerable.SelectIterator [TSource, TResult] (IEnumerable`1
source, Func 3 selector) +MoveNext()
at
System.Collections.Generic.LargeArrayBuilder 1.AddRange(IEnumerabl
e`1 items)
at
System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable
1 source)
at pkNX.WinForms.GenericEditor 1..ctor(Func'2 loadCache, Func 3
nameSelector, String title, Action 1 randomizeCallback, Action
addEntryCallback, Boolean canSave) in
D:\a\1\s\pkNX.WinForms\Subforms\GenericEditor.cs:line 27
at pkNX.WinForms.GenericEditor 1..ctor(DataCache 1 Cache, String[]
names, String title, Action randomizeCallback, Action
addEntryCallback, Boolean canSave) in
D:\a\1\s\pkNX.WinForms\Subforms\GenericEditor.cs:line 18
at pkNX.WinForms.Controls.EditorSWSH.EditItems() in
D:\a\1\s\pkNX.WinForms\Main Editor\EditorSWSH.cs:line 522
at System.RuntimeMethodHandle.InvokeMethod(Object target,
Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object
obj, BindingFlags invokeAttr)

**Comment by kwsch** [comment]
Did you provide the most recent personal data, from the latest game patch data? The program won't work unless you give it the most recent game data, rather than v1.0.0

**Comment by ItsJustLori** [comment]
> Did you provide the most recent personal data, from the latest game patch data? The program won't work unless you give it the most recent game data, rather than v1.0.0

I have installed game version 1.2.1

**Comment by kwsch** [comment]
Doesn't matter what you have installed; you need to dump the entire game as well as all the latest game files for pkNX to use. If you didn't dump the patch content and merge it in, then you get this set of error messages.

**Comment by ItsJustLori** [comment]
> Doesn't matter what you have installed; you need to dump the entire game as well as all the latest game files for pkNX to use. If you didn't dump the patch content and merge it in, then you get this set of error messages. This is mentioned in the readme:
> 
> > For Sword, Shield, Scarlet, and Violet, pkNX operates under the assumption that your dumped ROM includes the latest available update data.

I took the game, with version 1.2.1 and both DLC's and did a romfs dumb. Then I had the choice of “Complete”, or “Folder Structure Only”, where I chose “Complete”. What do I have to do differently, or what is missing and how do I get it?

**Comment by kwsch** [comment]
Are you using the latest build? The stacktrace you posted refers to line 87, which does not do what your stacktrace claims it is doing.

https://github.com/kwsch/pkNX/blob/5b5a196bdbea0b4855760b516b186fb8df363117/pkNX.Structures/Personal/Interfaces/IPersonalTable.cs#L87

**Comment by ItsJustLori** [comment]
If you mean the latest build of pkNX, than yes. I went to the top of this selection and downloaded it.
![image](https://github.com/user-attachments/assets/d9012fa6-d547-43ab-9ab2-cd861494d46c)

**Comment by kwsch** [comment]
Check the size of `\bin\pml\personal\personal_total.bin`. It should be 209,792 bytes (205KB).

**Comment by ItsJustLori** [comment]
It is

**Comment by kwsch** [comment]
Delete any pkNX-local copy of the file to ensure the program is reading it from your aforementioned dump, rather than a layeredfs copy (like an older patch's file).

**Comment by ItsJustLori** [comment]
Seems like this fixed it. I no longer get an error and everything can be opened. Thank you very much for your help. 🙏
