### ISSUE TITLE
Trainer randomizing in SwSh doesn't check Pokémon availability

### ISSUE THREAD

**Issue by Glazelf** [kwsch/pkNX#38]
Pokémon that aren't available in the game will show up in the randomization process for trainers (not for wild Pokémon).
![Screenshot_772](https://user-images.githubusercontent.com/35176230/69858163-b980b800-1291-11ea-9f0c-38ac50fc8b54.png)

**Comment by sora10pls** [comment]
This was also fixed with #41, so it can be closed @kwsch
