### ISSUE TITLE
Randomizing Field Items Pokemon Sword and Shield

### ISSUE THREAD

**Issue by nvbeusekom** [kwsch/pkNX#383]
Hi all,

I am trying to randomize field items in Pokemon Sword and Shield by coding it into the `Randomize()` function for the Placement form.
I figured out that the items you find are described with `ulong` values in the `Flags` field in:

pkNX.Structures.FlatBuffers.SWSH/Schemas/Placement/PlacementZoneFieldItemHolder.fbs

and that the amounts are described in the `Items` field. I have managed to change the items by copying other `ulong`s, that I found during debugging, into the `Flags` field.

However, everywhere else in the code (it seems that) items are described simply by integers, or `ushort`s. 

I could simply gather a list of `ulong`s of findable items and randomize those, but I was hoping to extend the list of findable items to add, for example, Master Balls as being findable in the field, based on the Legal Item List.

So my question is: would someone have any idea how these `ulong` values could be computed for any item?

Many thanks in advance

**Comment by sora10pls** [comment]
`romfs/bin/pml/item/item_hash_to_index.dat` stores all of this data in an easy to interpret table. Structure detailed below.

u32 numItems

Then a table:
length 0x10 * numItems
u64 hash
u64 item ID

Full parse here: https://gist.github.com/sora10pls/655af1165dceb4fdc890d9329249471a

**Comment by nvbeusekom** [comment]
Thank you so much 🙏 with this I got it to work!
