### ISSUE TITLE
Pknx "invalid folder loaded"

### ISSUE THREAD

**Issue by Mrgamer2240** [kwsch/pkNX#385]
I have the "Magic number" of 50494 and Pknx won't open giving me a message saying "invalid folder loaded unable to recognize game data" any solutions? I also have the folders in order "Game ID" "RomFS" and "ExeFS".

**Comment by kwsch** [comment]
The error message you posted is only given for when a `file` is opened, not a `folder`. When opening a folder, it will open things. Do not select a `file`.

**Comment by Mrgamer2240** [comment]
I'm opening the the Folder containing RomFS and ExeFs, it loads for a bit, then gives me the error message. I'm not opening a file but I get the message regardless.
