### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by locomain** [kwsch/pkNX#4]

**Comment by locomain** [comment]
![image](https://user-images.githubusercontent.com/1795993/48730536-f3f55500-ec3a-11e8-80bd-22758236e391.png)

yeah, a lot.

**Comment by ThatNerdyPikachu** [comment]
you sure you're opening the right file?

**Comment by evandixon** [comment]
Do you have the .Net Core SDK installed?

**Comment by locomain** [comment]
> you sure you're opening the right file?

Yeah, the sln right?

**Comment by locomain** [comment]
> Do you have the .Net Core SDK installed?

I need to double check on that. will do so when i get home.
