### ISSUE TITLE
General Sword and Shield Bugs/Potential Additions

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pkNX#40]
**Edit (12.16.2019):** Several bugs have been fixed and have therefore been removed from the original post.

A few of the bugs I've encountered with pkNX recently. This issue serves as a compilation of what needs to be fixed.
* Editing Gifts can crash the game
  * Editing multiple values at a time can lead to this crash
    * `Species`, `Ball`, and `CanGigantamax` are what I've tested this with
  * Filesize can change drastically (related?)

**Comment by kwsch** [comment]
File size change is due to incorrect field sizes (byte vs int) in flatbuffer definitions

**Comment by SnakeDeath** [comment]
not sure if these related but it happens when changing the trade pokemon , looks 
like the .bin file is not generated
![image](https://user-images.githubusercontent.com/25617671/71684722-4940e700-2da7-11ea-9e1e-18080485ba2f.png)

**Comment by eliKnaffo** [comment]
my PkNX saves both games as the first version of Sword and i cant play edited games anymore no idea how to fix this

**Comment by sora10pls** [comment]
@eliKnaffo Dump the 1.1.0 patch and edit that, support for it and Galarian Slowpoke was added recently.

As for which version is saved, pkNX currently defaults to Sword (no code to differentiate the two as of now, unlike LGPE). If you’re playing Shield, just rename the outputted Title ID folder to match Shield’s instead of Sword’s.
