### ISSUE TITLE
"Dump Table" button in "Pokémon", "Items" and "Moves" are not working

### ISSUE THREAD

**Issue by Asia81** [kwsch/pkNX#5]
It does nothing, so I can't dump these tables.
Any fix?

**Comment by kwsch** [comment]
Might take a second or two (wait for the sound), but it dumps it to your clipboard. You have to paste it somewhere (excel/open office calc) for it to be viewed.

**Comment by Asia81** [comment]
I guess there is some bugs, no? That boolean thing.
https://nsa39.casimages.com/img/2018/11/22/181122012040663483.png

Also, it's not possible to dump to a proper .txt file, as in common or script?
