### ISSUE TITLE
README inaccurate - seems like a C# 8 compiler is required

### ISSUE THREAD

**Issue by jugolm** [kwsch/pkNX#51]
The README file says a compiler that supports C# 7 can build the program, but when trying to build it an "Error CS1617: Invalid option '8.0' for /langversion when trying to compile" appears. Upon inspection it's clear that the project uses C# 8 which means having to download VS19.

Please clarify this in the README, or release an updated compiled binary, as the link provided in [here](https://projectpokemon.org/home/forums/topic/48647-pknx-nintendo-switch-rom-editor-randomizer/) is largely outdated.

Thanks.

**Comment by kwsch** [comment]
The link provided has been updated; you can access it via github with the green checkmark next to a given commit, or via the url on the thread.

**Comment by jugolm** [comment]
Thanks, sorry I bother you again but I still can't download the builds - if I access it through the green checkmark it says "Build not found". If I do it through the projectpokemon link, the screen "Pipelines > Runs" gets stuck forever.
Thanks!
