### ISSUE TITLE
Galarian Slowpoke

### ISSUE THREAD

**Issue by Shinyuusha** [kwsch/pkNX#55]
I am using moveset mods and when I use Low Amp Toxtricity, it doesnt learn its original moves. It learns Shadow Ball and Giga Drain from Pumpkaboo's learnset. How can I fix this to prevent the files from misreading in layeredfs? I know the 1.1 update adds to the file list, right? So should I remove the Slowpoke one?

**Comment by sora10pls** [comment]
Currently, entries 001 (Bulbasaur) to 914 (Galarian Rapidash) remain unchanged. As of Ver. 1.1.0, Galarian Slowpoke was added making it entry 915, shifting everything starting from Galarian Farfetch'd up by 1.

1154 used to be Toxtricity-1, but it is now Sinistea-1 (reason is explained above). Your mods will need to be renamed to match the new entries, and this will likely happen again as more DLC is released for the games in June and Fall later this year. I recommend Bulk Rename Utility.

Not an issue with pkNX, this can be closed.
