### ISSUE TITLE
sword shield gift trade static randomizing

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/pkNX#57]
hi. i wonder if it is possible to add a randomizer for these editors please since let's go has them. if not please could you point me to the direction of me adding it myself thank you. i am not familiar with flatt buffers but would like this alot

**Comment by sora10pls** [comment]
If and when this does get implemented, there are a few things to note.

- Zacian/Zamazenta shouldn't be randomized
  While they can be, this makes the Max Raid Battle against Eternatus unreasonably difficult
- Eternamax Eternatus cannot be randomized
  The game crashes trying to load the Max Raid Battle if it is modified
- Fields for `Moves` and `RelearnMoves` should all be set to `0`
  Some Statics and Trades have fixed Moves, this is done to ensure they have good Movesets
- Gift Pokémon where `CanGigantamax == true` should be swapped with other Gigantamax Species
  See (this will be updated over time as DLC is released, as it is missing Part 1's Gigantamaxes): https://github.com/kwsch/pkNX/blob/dc9563f0004fa50fe5b1d355e72277aafeba7b6e/pkNX.Structures/Legality/Tables8.cs#L202-L230
