### ISSUE TITLE
problems when I edit trainers

### ISSUE THREAD

**Issue by iser-sg** [kwsch/pkNX#61]
Hello! I have a problem .. when I edit trainers sometimes it is not saved, when I go out and re-enter the changes have not been saved even though I give it to save. Does anyone know what the problem is? I have downloaded the pknx again and it keeps happening to me. 
I hope not to disturb, it is not my intention ... THANKS

**Comment by kwsch** [comment]
[Refer to the readme](https://github.com/kwsch/pkNX/blob/64909ee7acc843a00420f58631ad5ce88bb99d5d/README.md):

> To lessen read/write lag, data is only saved when the user cleanly quits the program.
