### ISSUE TITLE
Changes made do not apply

### ISSUE THREAD

**Issue by PeitaX** [kwsch/pkNX#63]
I have a problem. I randomized some things and added the changes to see if everything worked correctly, and it certainly worked perfectly, the problem is that now I have continued modifying things in the game, and I cannot apply the changes I made, there are only the changes I made the first time , the latest changes do not apply. The first time the folder I put in the SD of the switch disappeared, but the new one does not disappear ... how can I apply the changes I made ?? thanks! what you do is incredible!

**Comment by kwsch** [comment]
Refer to the readme. Changes are only saved when you quit the program.

Be sure that you are placing the files on your console correctly. Doing those things wrong is not an issue with pkNX.
