### ISSUE TITLE
Invalid Folder / Game cannot be recognized (Pokemon Sword)

### ISSUE THREAD

**Issue by Christianwidjaya** [kwsch/pkNX#64]
I know you probably said there's must be exeFS and romFS folder in the folder we have to choose, but it has the folder and the content were extracted with hactool (along with the update). First i tried to load without the update, doesn't work with this structure, then i extract the update and it still doesnt work. Using latest commit (666-meadow) from pipelines and romFS (along with the update) has 41971 files. Idk what's wrong

**Comment by kwsch** [comment]
The program expects the romfs folder and exefs folder and a certain count of files.

https://github.com/kwsch/pkNX/blob/dc9563f0004fa50fe5b1d355e72277aafeba7b6e/pkNX.Game/GameLocation.cs#L65-L66

Any other count will be unrecognized by the program.

**Comment by Christianwidjaya** [comment]
Upon extracting 1.2.0 i got 46.897 files, checking the game location.cs its only 46.867 files, so it's basically a "sweetspot" instead of range which should also works?

**Comment by sora10pls** [comment]
No, the program expects the exact filecount present in the ROM. You have a bad dump and should try extracting the contents using [hactool](https://github.com/SciresM/hactool/releases).
