### ISSUE TITLE
Feature idea to fix current bug

### ISSUE THREAD

**Issue by Uzephi** [kwsch/pkNX#66]
It seems pkNX saves the folder as LGP and Sword IDs respectively. I tried randomizing my LGE and Shield games and the output folder is saved in LGP and Sword instead of LGE and Shield. To combat this, can we have the program output both games LGP/E and sw/sh ID folders to prevent user oversight and convenience?

**Comment by kwsch** [comment]
If we duplicated the folder-files, which folder will the user take? They still need to know the title ID.

Without having a detection mechanism for "what game is this", can't really make things easier for the user.
