### ISSUE TITLE
How to edit Drop tableID in Raid Encounters ???

### ISSUE THREAD

**Issue by edwarbad23** [kwsch/pkNX#67]
Hi, I will do a HackRom but I need help, I need edit the raids encounters but in specially the drop after the raid battle but only  appears numbers (see image), plz if someone know how to do it, I will really aprreciate, thnx

**Comment by kwsch** [comment]
pkNX only allows edits for the raid encounters, not the post-battle rewards.

Editing the raid content for sharing online is an easy way to get banned if GameFreak/Nintendo performs an audit of hosted raids.
