### ISSUE TITLE
Raid Bonus Rewards form question

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/pkNX#70]
I can't find the WinForms about the drop bonus table, where is it?
I want to add some component and function

**Comment by kwsch** [comment]
Most of the "dumb" editors use the `GenericEditor` form. This form is generic, and doesn't have any special logic that corresponds to the class that instantiated it.

If you want advanced function for an editor, I suggest you make a separate (dedicated) editor for the content you are wishing to modify.
