### ISSUE TITLE
Crashes Sword Game after Several Launches

### ISSUE THREAD

**Issue by Juno87** [kwsch/pkNX#72]
Having the mod folder in contents while closing and reopening Pokemon Sword game a few times crashes atmostphere with the "panic occurred while running atmostphere" error.

**Comment by kwsch** [comment]
> panic occurred while running atmostphere

this is pkNX, not atmosphere.

**Comment by Juno87** [comment]
Sorry. Posted because the pkmn sowrd mod folder from pkNX is causing the issue. Without it everything works fine.
