### ISSUE TITLE
The wild editor doesn't randomize

### ISSUE THREAD

**Issue by Jordito12** [kwsch/pkNX#76]
Every time I click the randomize button on the wild editor, it keeps playing that one windows beep and doesn't do any randomization. It allows me to manually edit them but doesn't randomize, everything else that has an option for randomization works but not the randomization for the wild editor. SWSH, I downloaded it from the pipeline

**Comment by sora10pls** [comment]
Make sure you're using the latest commit (LGPE randomization was broken but recently got fixed), and for the future please specify which game.

I'm unable to replicate this in both LGPE and SWSH.
![image](https://user-images.githubusercontent.com/17801814/83076354-5e166380-a043-11ea-93ee-79a340835c9c.png)
![image](https://user-images.githubusercontent.com/17801814/83076284-4343ef00-a043-11ea-9161-dc1889100f82.png)

**Comment by Jordito12** [comment]
Don't what I did but it worked

**Comment by Jordito12** [comment]
Maybe I was mistaken and didn't pay enough attention because I was left with the impression that it would take a bit of time to randomize it the same way it does for the moves

**Comment by sora10pls** [comment]
Randomization is pretty much instant with wild editing. Some editors may take a bit longer depending on how many settings are present.

Closing since it was working all along.
