### ISSUE TITLE
[Bug] Randomizing SWSH Learnsets crashes the program

### ISSUE THREAD

**Issue by PeitaX** [kwsch/pkNX#77]
when you press the randomize button in the movements the program stops working and I have to close it. the changes are not saved, why does that happen? can it be solved? THANK YOU!

**Comment by timy432** [comment]
I had the same issue. I just let the program run for about 15 minutes on not responding after hitting randomize and it eventually loaded and allowed me to save.

**Comment by kwsch** [comment]
Closed by the latest commits.
