### ISSUE TITLE
Static Always Shiny not Work

### ISSUE THREAD

**Issue by Stoned1337** [kwsch/pkNX#8]
Always Shiny on the Static Editor Doesn´t work. 
And no new or Edited Files in TitleID Folder Appear.

**Comment by kwsch** [comment]
Yes, we know :)

The game only acknowledges the 'never shiny' value; everything else is random.
Be sure you are using the latest version of the program (with updated dll files).

**Comment by Stoned1337** [comment]
Yes have forget to close the tool. 

Thanks
