### ISSUE TITLE
STAB, STABPercent, and STABFirst doesn't do anything, and other learnset issues

### ISSUE THREAD

**Issue by tommaniacal** [kwsch/pkNX#80]
If you randomize the types of Pokemon, randomizing the learnsets by STAB doesn't do anything. It doesn't seem to be pulling from the Pokemon's original typing either. Setting stab to 50%:
![Screenshot (190)](https://user-images.githubusercontent.com/31083594/83706281-b36ee980-a5dc-11ea-92f2-6202fbb8f6d8.png)
![Screenshot (192)](https://user-images.githubusercontent.com/31083594/83706300-bb2e8e00-a5dc-11ea-893a-6779d995bd21.png)
![Screenshot (193)](https://user-images.githubusercontent.com/31083594/83706311-c08bd880-a5dc-11ea-90e6-9cb8954bde7a.png)

Also, if you set pokemon to start with 4 moves, it appears to just take the next three learned moves and set them to level 1, making them have a big gap in their learnset. Would it be possible for this option to instead _add_ three level 1 moves, and keep the next three where they are?

Lastly, is it possible for randomized learnsets to omit max moves? All of the damaging ones are 1 BP
so they're completely useless.

**Comment by kwsch** [comment]
Closed by the latest commits.
