### ISSUE TITLE
A numeric comparison was attempted on "$(MsBuildMajorVersion)" that evaluates to "" instead of a number, in condition "($(MsBuildMajorVersion) < 16)".

### ISSUE THREAD

**Issue by tommaniacal** [kwsch/pkNX#81]
Whenever I build the solution, I get this error. I'm using Visual Studio Community. It still builds an executable, but it doesn't actually open anything. How do I fix this?

**Comment by kwsch** [comment]
Be sure you have the startup project selected as pkNX.WinForms, and that you've tried to Rebuild Solution until it has completely built.
