### ISSUE TITLE
Randomizing trainers not working

### ISSUE THREAD

**Issue by tommaniacal** [kwsch/pkNX#82]
Hello, when I randomize trainers in PKNX it seems to save the changes (I click save and exit with the 'X' button every time, and looking at each trainer shows that they were randomized) but when loading into the game the trainers are unchanged. Everything else I've done in PKNX carries through into the game, but trainers don't

**Comment by sora10pls** [comment]
Unable to replicate, probably not a pkNX issue. Make sure your folder structure is correct.
![image](https://user-images.githubusercontent.com/17801814/83826258-76245d80-a6a9-11ea-9f25-5706f4408b25.png)
![image](https://user-images.githubusercontent.com/17801814/83826292-876d6a00-a6a9-11ea-8cc4-32c1f8d12c50.png)
