### ISSUE TITLE
"Could not find a part of the path"

### ISSUE THREAD

**Issue by BoomBoxKid173** [kwsch/pkNX#84]
'C:\Users\(PC USER)\Pokemonfiles\ROMFS\bin\message\English\common'.

This is the error I get when I try running my folder in the program.

![13331ecdd6bb1a7122190a232438a811](https://user-images.githubusercontent.com/44116609/84982560-9ff37080-b0fc-11ea-9150-023b79bc4032.jpg)

**Comment by BoomBoxKid173** [comment]
And the weird thing is, it's looking for a bin inside RomFS, but I don't have a bin there, I have my game file which in turn has the bin inside of that.

https://gyazo.com/07a458519e67645b43df881d63aefdd0

**Comment by kwsch** [comment]
pkNX expects a valid ROM dump with all files unpacked correctly.
