### ISSUE TITLE
Unable to load the updated title obtained from pkNX

### ISSUE THREAD

**Issue by brianlin0725** [kwsch/pkNX#87]
I managed to get the dump file for pokemon shield version 1.2.0 and was able to edit it
. but when i put the output file from PkNX to my switch. I can't open the game. Every time i try to, it says the software closed because an error occured

**Comment by kwsch** [comment]
Not an issue with pkNX.

**Comment by eppao** [comment]
I'm having the same issue. @brianlin0725 Did you find a solution?

**Comment by kwsch** [comment]
Read the forums.

**Comment by eppao** [comment]
> Read the forums.

I'm sorry for my idiocy, but where on the forums does it talk about loading mods?
