### ISSUE TITLE
Buil

### ISSUE THREAD

**Issue by KaiserTialoc** [kwsch/pkNX#88]

**Comment by KaiserTialoc** [comment]
Hi 
The version of PKNX that I have built is no longer launching on windows 10
It was working a few days ago but now doesn’t
I have tried multiple fixes including deleting and re building and regesitry edits
I also downloaded a prebuilt version and that loaded

Is there any reason why this has stopped working?
Also all windows updates have been installed

Thanks in advance

**Comment by kwsch** [comment]
Works fine. 

Be sure you're trying to run the program with all required dll files, not just the .exe
