### ISSUE TITLE
"Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by eppao** [kwsch/pkNX#90]
I was following a method on randomizing Pokemon Shield from a video (https://www.youtube.com/watch?v=W22dRFRTk4w) and I'm having trouble solving this. This might be a problem on my end, but I assume there might be something wrong with the code (?)

![sdfsdf2](https://user-images.githubusercontent.com/67838156/86518195-8d1bb400-bdfd-11ea-8681-f454bdd60fe1.png)

![sdkfsdf](https://user-images.githubusercontent.com/67838156/86518185-61003300-bdfd-11ea-98e9-101c1ede30b4.PNG)

**Comment by sora10pls** [comment]
#85 
Follow [my tutorial on the forums](https://projectpokemon.org/tutorials/rom/switch-pokemon-games-hacking-tutorials_158/dumping-games-for-pknx-rom-editingrandomization-r111/) instead.
