### ISSUE TITLE
Night/Day cycle in story mode

### ISSUE THREAD

**Issue by Prototaipei** [kwsch/pkNX#93]
Hello, currently in SWSH the day and night cycle is locked during the story mode. For example, the game is always locked at 'day' during the first few quests in the starter town. Is there any way to change this ? And if so will this feature be added ?

**Comment by sora10pls** [comment]
This type of feature request is beyond the scope of the program. Would likely require much more than just a simple edit, as we can't even edit scripts for any of the recent (3DS/Switch) games.

**Comment by Prototaipei** [comment]
Alright, thank you for your response. It is appreciated :)
