### ISSUE TITLE
SwSh pre-1.2.0 support broken

### ISSUE THREAD

**Issue by Tiddlywinkss** [kwsch/pkNX#95]
If you try to load a version of Sw/Sh before version 1.2.0 (Isle of Armor update), the game hits an error when loading personal info.

The problem is that the [Initial Isle of Armor support](https://github.com/kwsch/pkNX/commit/7fd6fe849b574784e35d86d5b76bf34c81abad9d#diff-a21612ecc31ac0085403d0a384248ea7) update changed the entry size in PersonalInfoSWSH, but the GameLocation class still supports pre-IoA versions, where the entry size should still be smaller.

ETA: ...Perhaps I should have noticed the line that was also added in the readme that pkNX assumes you have v1.2+. Still, trying to load an old ROM raises an unhandled error and even if you just want to deprecate support, those cases could be handled properly.

**Comment by kwsch** [comment]
Working as intended.

Personal Info size changed.
