### ISSUE TITLE
Request: Wild Area (both) Item Spawns

### ISSUE THREAD

**Issue by Th3Alic3** [kwsch/pkNX#96]
Hello pkNX Team,

The current build of pkNX does not have an option for Items. (I'm on v1.2.1 of the Sword/Shield games if that makes a difference.)

I would like to request an Items section added to the list of elements which can be modified/randomized for Sword/Shield.

The Items currently requiring editing/randomized options would include
- TM locations (Gym Victory Gift, Overworld Pickup, NPC Gift, and Shop Purchases)
- Overworld (Mainland) visible Items
- Overworld (Wild Area) visible Items
- Overworld (Isle of Armor) visible Items
- Overworld (Mainland) Hidden Items
- Overworld (Wild Area) Hidden Items (Pools as each one is linked to a Pool)
- Overworld (Wild Area) Hidden Items (replaced with Wishing Piece %)
- Overworld (Isle of Armor) Hidden Items (Pools as each one is linked to a Pool)

At the time, I am not looking for full Randomization. I was just hoping to adjust the mainland Wild Area % to replace the Hidden Items with a Wishing Piece.

**Comment by kwsch** [comment]
Scripting is not researched.

**Comment by Th3Alic3** [comment]
What does that mean and why was this feature REQUEST closed?

**Comment by sora10pls** [comment]
If something is not researched sufficiently, editors for those features can't be added into the program.

Scripting refers to commands the game reads to have certain actions be performed. For example, this issue requests field item editing, which would require script editing (object on map => interact => item given => object hidden).

**Comment by Th3Alic3** [comment]
Yes, I understand "something is not researched sufficiently" means that it CURRENTLY cannot be added. It does not mean it cannot ever be added.

I am most concerned with the Wild Area hidden item drops. The following is observable to be true for these hidden item drops:
- The game stores as an in-game TRUE/FALSE value for picked up.
- The game resets the in-game TRUE/FALSE value for picked up when the frame is advanced
- The frame determines if there is an item available by the frame
- The frame determines the value of the item to be found
- The game has a pool items associated with it.

So, I believe the equivalent (of your example, @sora10pls) for the Wild Area would would be:
object on map => interact =>
check picked up value => if not picked up => check frame/seed => determine item given =>
item given => object hidden

Since the item pools have to be stored somewhere in the code as a table to reference, I believe what I am asking is:

Does this thread being closed mean that pkNX will NEVER impliment the edit for the item pools even if the item table is found and researched?

**Comment by sora10pls** [comment]
We currently have no interest in researching this. Even with pk3DS for the Generation 6 and 7 games, we don't have proper script editing available (yet).

If you wish to research this, be our guest. The project is open source and you're free to contribute, as is anyone else interested in having this implemented.
