### ISSUE TITLE
pkNX expects only folders for inside of RomFS

### ISSUE THREAD

**Issue by PP-theSLAYER** [kwsch/pkNX#97]
**Summary:**
pkNX detection should be reworked a bit.

**Main Gist:**
I was told that by using HACGUI, one actually extracts the license file info into RomFS as well.
As such, even if you had a valid rom dump, pkNX would not be able to detect the game.
(and to reiterate, this is a good dump, except HACGUI did the extraction, and placed the license file in RomFS).

While this issue can be avoided by simply removing those files, users may not be aware of this, and be stumped by this issue for a while. So having pkNX ignore those files, or only check for the correct folders, would be optimal in my opinion.

**Replication:**
While I do not have photos of this issue, I was able to recreate it.
Game detected:
![image](https://user-images.githubusercontent.com/23535344/93016240-1c65f480-f603-11ea-8658-c36d6eab798a.png)
Game not detected by adding a blank file.
![image](https://user-images.githubusercontent.com/23535344/93016255-37d0ff80-f603-11ea-9960-8ddb24e3d102.png)

**Comment by sharrenskunk** [comment]
I get this error also, the first time I dumped the game it worked. I wanted to redo the process a few days later because the patch crashed the game and tried to re-dump. Nxdumptool gave me an error that got patched oct-1st/today and tried to re-dump the game. Not sure if it was missing some files because it gave me the same error in the picture provided by op. 

Any idea as to why it's bugging out?

**Comment by kwsch** [comment]
We've always had success with hactool, no other metadata has ever been required.

The checks used by pk3DS and pkNX check for file count within the extracted ROM file structure.

**Comment by sharrenskunk** [comment]
Just rdumped the data and it was all good.

**Comment by kwsch** [comment]
Putting extra files into the romfs that aren't from the romfs is bad behavior; they shouldn't be doing that.

Future readers: Just delete the extra unnecessary files that aren't actually romfs files, and everything will work fine (as explained above).
