### ISSUE TITLE
Pokemon Sword Randomization

### ISSUE THREAD

**Issue by droidforever** [kwsch/pkNX#99]
I am having problems with using this application.  Here are my steps.  I have a dump of an .xci file from Pokemon Sword with the update 1.2 included.  I extracted this  using hactool.  Found the file with the largest size and matched that to the extracted folders.  Opened pkNX and tried to open that folder and I get this:

![image](https://user-images.githubusercontent.com/7252156/96447375-cecf3f80-11df-11eb-9a49-a0ffc2bd33ab.png)
How can I fix this or what am I doing wrong?  I had no problem with Let's Go Pickachu or Evee.  This is using the latest version of pkNX.

**Comment by sora10pls** [comment]
You have an invalid dump (likely missing the 1.2.0 update). Since you didn't post the full exception, we can assume that it reads:
```csharp
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at pkNX.Structures.PersonalTable.SplitBytes(Byte[] data, Int32 size)
```
Related: #85, #90
